### ISSUE TITLE
ClassNotFoundException while deploying on Oracle WebLogic

### ISSUE THREAD

**Issue by stieler-it** [typetools/checker-framework#1839]
Hello,

we experienced a problem while upgrading our Spring Boot application. After a long search we found out that it was caused by an upgrade of the transient dependency Guava from `18.0` to `23.5-jre`, which now includes the transient dependency `checker-qual` in version `2.0.0`.

When the application is deployed on Oracle WebLogic (Version `12.2.1.2.0`), the following exception prevents the start:

```
java.lang.ClassNotFoundException: afu.com.sun.source.tree.Tree$Kind
	at weblogic.utils.classloaders.GenericClassLoader.findLocalClass(GenericClassLoader.java:1026)
	at weblogic.utils.classloaders.GenericClassLoader.findClass(GenericClassLoader.java:987)
	at weblogic.utils.classloaders.ChangeAwareClassLoader.findClass(ChangeAwareClassLoader.java:83)
	at weblogic.utils.classloaders.GenericClassLoader.doFindClass(GenericClassLoader.java:608)
	at weblogic.utils.classloaders.GenericClassLoader.loadClass(GenericClassLoader.java:540)
	at weblogic.utils.classloaders.GenericClassLoader.loadClass(GenericClassLoader.java:493)
	at weblogic.utils.classloaders.GenericClassLoader.loadClass(GenericClassLoader.java:470)
	at weblogic.utils.classloaders.ChangeAwareClassLoader.loadClass(ChangeAwareClassLoader.java:62)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at sun.reflect.annotation.AnnotationType$1.run(AnnotationType.java:112)
	at sun.reflect.annotation.AnnotationType$1.run(AnnotationType.java:109)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:109)
	at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:85)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:266)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotations(Class.java:3446)
	at weblogic.application.utils.annotation.AnnotationAncestry.isExtendedAnnotationDeep(AnnotationAncestry.java:107)
	at weblogic.application.utils.annotation.AnnotationAncestry.isExtendedAnnotation(AnnotationAncestry.java:93)
```

We could fix this by excluding `checker-qual` from our dependencies by inserting this at the beginning of our `dependencyManagement`:

```
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>23.5-jre</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.checkerframework</groupId>
                        <artifactId>checker-qual</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
```

Although this solved our problem and it looks more like a WebLogic issue I thought this might be of interest to you or other users experiencing the same problem.

**Comment by stieler-it** [comment]
Update:
Guava `24.0-jre` depends on `checker-compat-qual` version `2.0.0` which also has no problems on WebLogic.

So adding the following at the beginning of dependencies also fixes it:
```
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>24.0-jre</version>
            </dependency>
```

Thus I'm closing this issue.

**Comment by mernst** [comment]
Thanks for reporting the fix, to help other people who might encounter the same issue.
