### ISSUE TITLE
The following files could not be located: jdk7.jar

### ISSUE THREAD

**Issue by GoogleCodeExporter** [typetools/checker-framework#188]
```
When I try to run the checker framework using the Eclipse plugin, I get the 
following error message:

javac output:
Exception in thread "main" java.lang.RuntimeException: The following files 
could not be located: jdk7.jar
	at checkers.util.CheckerMain.assertFilesExist(CheckerMain.java:428)
	at checkers.util.CheckerMain.<init>(CheckerMain.java:93)
	at checkers.util.CheckerMain.main(CheckerMain.java:37)

I don't remember using this file before. I'm not sure where I have to put the 
jdk7.jar file.
```

Original issue reported on code.google.com by `reprogra...@gmail.com` on 30 Dec 2012 at 12:10

**Comment by wmdietl** [comment]
The Eclipse plug-in has been significantly rewritten since there last was a comment on this issue.
I assume that it has been fixed. Please comment if you're still running into this.
