### ISSUE TITLE
Commented-out code in JavacRunner causes NPE

### ISSUE THREAD

**Issue by GoogleCodeExporter** [typetools/checker-framework#190]
```
JavacRunner provides more precise location information for reported problems. 
Thus, quick fixes only work with JavacRunner. I changed 
checkers.eclipse.actions.CheckerWorker.shouldUseJavacRunner() to return true. 
This switches the Eclipse plug-in from using CommandlineJavacRunner to 
JavacRunner. However, when I run a checker using the Eclipse plug-in, the 
plug-in throws the following exception:

eclipse.buildId=M20120914-1800
java.version=1.7.0_10
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.platform.ide

!ENTRY checker.framework.eclipse.plugin 4 0 2012-12-31 17:19:29.728
!MESSAGE Analysis exception
!STACK 0
java.lang.NullPointerException
    at org.eclipse.core.internal.runtime.Activator.getURLConverter(Activator.java:321)
    at org.eclipse.core.runtime.FileLocator.toFileURL(FileLocator.java:205)
    at checkers.eclipse.javac.JavacRunner.getLocation(JavacRunner.java:195)
    at checkers.eclipse.javac.JavacRunner.getOptions(JavacRunner.java:105)
    at checkers.eclipse.javac.JavacRunner.run(JavacRunner.java:74)
    at checkers.eclipse.actions.CheckerWorker.runChecker(CheckerWorker.java:125)
    at checkers.eclipse.actions.CheckerWorker.work(CheckerWorker.java:105)
    at checkers.eclipse.actions.CheckerWorker.run(CheckerWorker.java:83)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
```

Original issue reported on code.google.com by `reprogra...@gmail.com` on 31 Dec 2012 at 11:24

**Comment by mernst** [comment]
This issue is not being worked on, so I am closing it.
