### ISSUE TITLE
cannot build annotated_jdk due to missing sun.reflect.CallerSensitive

### ISSUE THREAD

**Issue by chengniansun** [typetools/checker-framework#2067]
In the latest release v2_5_3, the java/lang/Class was annotated with CallerSensitive. However, before this version, the annotation was not used. In our internal system, when we are trying to extract annotations from the stub class, we get the following error. Any advice is appreciated. 

Thank you. 

```java
Exception in thread "main" java.lang.Error: java.lang.ClassNotFoundException: sun.reflect.CallerSensitive
        at scenelib.annotations.io.classfile.ClassAnnotationSceneReader$AnnotationSceneReader.getAnnotationDef(ClassAnnotationSceneReader.java:263)
        at scenelib.annotations.io.classfile.ClassAnnotationSceneReader$AnnotationSceneReader.<init>(ClassAnnotationSceneReader.java:283)
        at scenelib.annotations.io.classfile.ClassAnnotationSceneReader$MethodAnnotationSceneReader.visitTypeAnnotation(ClassAnnotationSceneReader.java:1200)
        at scenelib.annotations.io.classfile.ClassAnnotationSceneReader$MethodAnnotationSceneReader.visitAnnotation(ClassAnnotationSceneReader.java:1194)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:930)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:445)
        at scenelib.annotations.io.classfile.ClassFileReader.read(ClassFileReader.java:206)
        at scenelib.annotations.io.classfile.ClassFileReader.read(ClassFileReader.java:200)
        at scenelib.annotations.io.classfile.ClassFileReader.read(ClassFileReader.java:172)
        at scenelib.annotations.io.classfile.ClassFileReader.main(ClassFileReader.java:116)
Caused by: java.lang.ClassNotFoundException: sun.reflect.CallerSensitive
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:187)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:292)
        at scenelib.annotations.io.classfile.ClassAnnotationSceneReader$AnnotationSceneReader.getAnnotationDef(ClassAnnotationSceneReader.java:255)
        ... 9 more
```

**Comment by wmdietl** [comment]
https://github.com/typetools/checker-framework/blob/master/checker/jdk/nullness/src/java/lang/Class.java
was converted from a stub file to full sources in https://github.com/typetools/checker-framework/commit/434228b6290fa96305029c5929ca4349c590ec08

The source now corresponds more closely to the Java 8 sources at http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/lang/Class.java
and the only difference are the Checker Framework annotations.

`@CallerSensitive` is a standard OpenJDK class http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/sun/reflect/CallerSensitive.java
and including the annotation in Class.java hasn't been a problem for our build of the annotated JDK.

In your stack trace I see `at java.base/`. Maybe you need to include an additional module to include `@CallerSensitive` on your classpath? Or maybe you need to open `java.base` for use of CallerSensitive by the Class.java compilation?

**Comment by chengniansun** [comment]
Thank you for the advice. Liam fixed it.
