### ISSUE TITLE
NullPointerException when running infer-and-annotate.sh tool

### ISSUE THREAD

**Issue by shashiranjan** [typetools/checker-framework#2239]
I was following the steps for Whole-program inference to infer the types. But I was getting nullPointerException  for infer-and-annotate.sh script. Can you please check if I am missing something in command or is it a bug in tool?

Steps followed from here: https://checkerframework.org/determinism-checker-manual/manual.html#whole-program-inference

Command that I ran: 
```
sh ../checker-framework/checker/bin/infer-and-annotate.sh "LockChecker,NullnessChecker" java/plume.jar:java/plume-core.jar:java/task_manager.jar:java/lib/junit-4.12.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/tools.jar -AprintErrorStack `find java/src/plume/ -name "*.java"``
```

```
f45c89b32ef5:plume-lib ranjansr$ sh ../checker-framework/checker/bin/infer-and-annotate.sh "LockChecker,NullnessChecker" java/plume.jar:java/plume-core.jar:java/task_manager.jar:java/lib/junit-4.12.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/tools.jar -AprintErrorStack `find java/src/plume/ -name "*.java"`
About to run: ../checker-framework/checker/bin/javac -d build/temp-whole-program-inference-output/ -cp java/plume.jar:java/plume-core.jar:java/task_manager.jar:java/lib/junit-4.12.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/tools.jar -processor LockChecker,NullnessChecker -Ainfer -Awarns -Xmaxwarns 10000  -AprintErrorStack  java/src/plume//ArraysMDE.java java/src/plume//BCELUtil.java java/src/plume//BibtexClean.java java/src/plume//ClassFileVersion.java java/src/plume//CountingPrintWriter.java java/src/plume//DeclarationAnnotations.java java/src/plume//DeterministicObject.java java/src/plume//Digest.java java/src/plume//EntryReader.java java/src/plume//FileCompiler.java java/src/plume//FileIOException.java java/src/plume//Filter.java java/src/plume//FuzzyFloat.java java/src/plume//GraphMDE.java java/src/plume//Hasher.java java/src/plume//ICalAvailable.java java/src/plume//Intern.java java/src/plume//IterableIterator.java java/src/plume//JWhich.java java/src/plume//LimitedSizeIntSet.java java/src/plume//LimitedSizeSet.java java/src/plume//Lookup.java java/src/plume//MathMDE.java java/src/plume//MultiRandSelector.java java/src/plume//MultiVersionControl.java java/src/plume//Option.java java/src/plume//OptionGroup.java java/src/plume//Options.java java/src/plume//OptionsDoclet.java java/src/plume//OrderedPairIterator.java java/src/plume//Pair.java java/src/plume//Partitioner.java java/src/plume//RandomSelector.java java/src/plume//RandoopMappedCalls.java java/src/plume//RegexUtil.java java/src/plume//SimpleLog.java java/src/plume//Stopwatch.java java/src/plume//StrTok.java java/src/plume//StringBuilderDelimited.java java/src/plume//TaskManager.java java/src/plume//TestPlume.java java/src/plume//TimeLimitProcess.java java/src/plume//Triple.java java/src/plume//Unpublicized.java java/src/plume//UtilMDE.java java/src/plume//WeakHasherMap.java java/src/plume//WeakIdentityHashMap.java java/src/plume//WeakIdentityPair.java java/src/plume//package-info.java
warning: The following options were not recognized by any processor: '[printErrorStack]'
java/src/plume/ArraysMDE.java:2052: warning: [method.guarantee.violated] @SideEffectFree method toString((@org.checkerframework.framework.qual.PolyAll :: java.lang.Object)[],boolean) calls method append(java.lang.String) with a weaker @ReleasesNoLocks side effect guarantee
    sb.append("[");
             ^
java/src/plume/ArraysMDE.java:2054: warning: [method.guarantee.violated] @SideEffectFree method toString((@org.checkerframework.framework.qual.PolyAll :: java.lang.Object)[],boolean) calls method append(java.lang.Object) with a weaker @ReleasesNoLocks side effect guarantee
      sb.append(a[0]);
               ^
java/src/plume/ArraysMDE.java:2056: warning: [method.guarantee.violated] @SideEffectFree method toString((@org.checkerframework.framework.qual.PolyAll :: java.lang.Object)[],boolean) calls method append(java.lang.String) with a weaker @ReleasesNoLocks side effect guarantee
        sb.append(", ");
                 ^
java/src/plume/ArraysMDE.java:2059: warning: [method.guarantee.violated] @SideEffectFree method toString((@org.checkerframework.framework.qual.PolyAll :: java.lang.Object)[],boolean) calls method append(char) with a weaker @ReleasesNoLocks side effect guarantee
          sb.append('\"');
                   ^
java/src/plume/ArraysMDE.java:2060: warning: [method.guarantee.violated] @SideEffectFree method toString((@org.checkerframework.framework.qual.PolyAll :: java.lang.Object)[],boolean) calls method append(java.lang.String) with a weaker @ReleasesNoLocks side effect guarantee
          sb.append(UtilMDE.escapeNonJava(elt));
                   ^
java/src/plume/ArraysMDE.java:2060: warning: [method.guarantee.violated] @SideEffectFree method toString((@org.checkerframework.framework.qual.PolyAll :: java.lang.Object)[],boolean) calls method escapeNonJava(java.lang.String) with a weaker @ReleasesNoLocks side effect guarantee
          sb.append(UtilMDE.escapeNonJava(elt));
                                         ^
java/src/plume/ArraysMDE.java:2061: warning: [method.guarantee.violated] @SideEffectFree method toString((@org.checkerframework.framework.qual.PolyAll :: java.lang.Object)[],boolean) calls method append(char) with a weaker @ReleasesNoLocks side effect guarantee
          sb.append('\"');
                   ^
java/src/plume/ArraysMDE.java:2063: warning: [method.guarantee.violated] @SideEffectFree method toString((@org.checkerframework.framework.qual.PolyAll :: java.lang.Object)[],boolean) calls method append(java.lang.Object) with a weaker @ReleasesNoLocks side effect guarantee
          sb.append(a[i]);
                   ^
java/src/plume/ArraysMDE.java:2067: warning: [method.guarantee.violated] @SideEffectFree method toString((@org.checkerframework.framework.qual.PolyAll :: java.lang.Object)[],boolean) calls method append(java.lang.String) with a weaker @ReleasesNoLocks side effect guarantee
    sb.append("]");
             ^
java/src/plume/ArraysMDE.java:2113: warning: [method.guarantee.violated] @SideEffectFree method toString((@org.checkerframework.checker.nullness.qual.Nullable :: java.util.Collection<?>),boolean) calls method append(java.lang.String) with a weaker @ReleasesNoLocks side effect guarantee
    sb.append("[");
             ^
java/src/plume/ArraysMDE.java:2116: warning: [method.guarantee.violated] @SideEffectFree method toString((@org.checkerframework.checker.nullness.qual.Nullable :: java.util.Collection<?>),boolean) calls method append(java.lang.Object) with a weaker @ReleasesNoLocks side effect guarantee
      sb.append(itor.next());
               ^
java/src/plume/ArraysMDE.java:2116: warning: [method.guarantee.violated] @SideEffectFree method toString((@org.checkerframework.checker.nullness.qual.Nullable :: java.util.Collection<?>),boolean) calls method next() with a weaker @ReleasesNoLocks side effect guarantee
      sb.append(itor.next());
                         ^
java/src/plume/ArraysMDE.java:2117: warning: [method.guarantee.violated] @SideEffectFree method toString((@org.checkerframework.checker.nullness.qual.Nullable :: java.util.Collection<?>),boolean) calls method hasNext() with a weaker @ReleasesNoLocks side effect guarantee
      while (itor.hasNext()) {
                         ^
java/src/plume/ArraysMDE.java:2118: warning: [method.guarantee.violated] @SideEffectFree method toString((@org.checkerframework.checker.nullness.qual.Nullable :: java.util.Collection<?>),boolean) calls method append(java.lang.String) with a weaker @ReleasesNoLocks side effect guarantee
        sb.append(", ");
                 ^
java/src/plume/ArraysMDE.java:2119: warning: [method.guarantee.violated] @SideEffectFree method toString((@org.checkerframework.checker.nullness.qual.Nullable :: java.util.Collection<?>),boolean) calls method next() with a weaker @ReleasesNoLocks side effect guarantee
        Object elt = itor.next();
                              ^
java/src/plume/ArraysMDE.java:2121: warning: [method.guarantee.violated] @SideEffectFree method toString((@org.checkerframework.checker.nullness.qual.Nullable :: java.util.Collection<?>),boolean) calls method append(char) with a weaker @ReleasesNoLocks side effect guarantee
          sb.append('\"');
                   ^
java/src/plume/ArraysMDE.java:2122: warning: [method.guarantee.violated] @SideEffectFree method toString((@org.checkerframework.checker.nullness.qual.Nullable :: java.util.Collection<?>),boolean) calls method append(java.lang.String) with a weaker @ReleasesNoLocks side effect guarantee
          sb.append(UtilMDE.escapeNonJava((String) elt));
                   ^
java/src/plume/ArraysMDE.java:2122: warning: [method.guarantee.violated] @SideEffectFree method toString((@org.checkerframework.checker.nullness.qual.Nullable :: java.util.Collection<?>),boolean) calls method escapeNonJava(java.lang.String) with a weaker @ReleasesNoLocks side effect guarantee
          sb.append(UtilMDE.escapeNonJava((String) elt));
                                         ^
java/src/plume/ArraysMDE.java:2123: warning: [method.guarantee.violated] @SideEffectFree method toString((@org.checkerframework.checker.nullness.qual.Nullable :: java.util.Collection<?>),boolean) calls method append(char) with a weaker @ReleasesNoLocks side effect guarantee
          sb.append('\"');
                   ^
java/src/plume/ArraysMDE.java:2125: warning: [method.guarantee.violated] @SideEffectFree method toString((@org.checkerframework.checker.nullness.qual.Nullable :: java.util.Collection<?>),boolean) calls method append(java.lang.Object) with a weaker @ReleasesNoLocks side effect guarantee
          sb.append(elt);
                   ^
java/src/plume/ArraysMDE.java:2129: warning: [method.guarantee.violated] @SideEffectFree method toString((@org.checkerframework.checker.nullness.qual.Nullable :: java.util.Collection<?>),boolean) calls method append(java.lang.String) with a weaker @ReleasesNoLocks side effect guarantee
    sb.append("]");
             ^
java/src/plume/ArraysMDE.java:2351: warning: [method.guarantee.violated] @Pure method noDuplicates(boolean[]) calls method add(E) with a weaker @ReleasesNoLocks side effect guarantee
      hs.add(n);
            ^
java/src/plume/ArraysMDE.java:2375: warning: [method.guarantee.violated] @Pure method noDuplicates(byte[]) calls method add(E) with a weaker @ReleasesNoLocks side effect guarantee
      hs.add(n);
            ^
java/src/plume/ArraysMDE.java:2399: warning: [method.guarantee.violated] @Pure method noDuplicates(char[]) calls method add(E) with a weaker @ReleasesNoLocks side effect guarantee
      hs.add(n);
            ^
java/src/plume/ArraysMDE.java:2423: warning: [method.guarantee.violated] @Pure method noDuplicates(float[]) calls method add(E) with a weaker @ReleasesNoLocks side effect guarantee
      hs.add(n);
            ^
java/src/plume/ArraysMDE.java:2447: warning: [method.guarantee.violated] @Pure method noDuplicates(short[]) calls method add(E) with a weaker @ReleasesNoLocks side effect guarantee
      hs.add(n);
            ^
java/src/plume/ArraysMDE.java:2471: warning: [method.guarantee.violated] @Pure method noDuplicates(int[]) calls method add(E) with a weaker @ReleasesNoLocks side effect guarantee
      hs.add(n);
            ^
java/src/plume/ArraysMDE.java:2496: warning: [method.guarantee.violated] @Pure method noDuplicates(double[]) calls method add(E) with a weaker @ReleasesNoLocks side effect guarantee
      hs.add(n);
            ^
java/src/plume/ArraysMDE.java:2520: warning: [method.guarantee.violated] @Pure method noDuplicates(long[]) calls method add(E) with a weaker @ReleasesNoLocks side effect guarantee
      hs.add(n);
            ^
java/src/plume/ArraysMDE.java:2543: warning: [method.guarantee.violated] @Pure method noDuplicates(java.lang.String[]) calls method add(E) with a weaker @ReleasesNoLocks side effect guarantee
      hs.add(a[i]);
            ^
java/src/plume/ArraysMDE.java:2566: warning: [method.guarantee.violated] @Pure method noDuplicates(java.lang.Object[]) calls method add(E) with a weaker @ReleasesNoLocks side effect guarantee
      hs.add(a[i]);
            ^
java/src/plume/ArraysMDE.java:2590: warning: [method.guarantee.violated] @Pure method <T>noDuplicates(java.util.List<T>) calls method add(E) with a weaker @ReleasesNoLocks side effect guarantee
      hs.add(a.get(i));
            ^
java/src/plume/ArraysMDE.java:2749: warning: [method.guarantee.violated] @Pure method isSubset(long[],long[]) calls method add(E) with a weaker @ReleasesNoLocks side effect guarantee
      setBigger.add(bigger[i]);
                   ^
java/src/plume/ArraysMDE.java:2781: warning: [method.guarantee.violated] @Pure method isSubset(double[],double[]) calls method add(E) with a weaker @ReleasesNoLocks side effect guarantee
      setBigger.add(bigger[i]);
                   ^
java/src/plume/ArraysMDE.java:2813: warning: [method.guarantee.violated] @Pure method isSubset(java.lang.String[],java.lang.String[]) calls method add(E) with a weaker @ReleasesNoLocks side effect guarantee
      setBigger.add(bigger[i]);
                   ^
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
	at com.sun.tools.javac.main.Main.compile(Main.java:559)
	at com.sun.tools.javac.main.Main.compile(Main.java:381)
	at com.sun.tools.javac.main.Main.compile(Main.java:370)
	at com.sun.tools.javac.main.Main.compile(Main.java:361)
	at com.sun.tools.javac.Main.compile(Main.java:56)
	at com.sun.tools.javac.Main.main(Main.java:42)
Caused by: java.lang.NullPointerException
	at org.checkerframework.framework.source.SourceChecker.logBugInCF(SourceChecker.java:759)
	at org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:972)
	at org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:494)
	at org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:182)
	at com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 5 more
Error: Could not find or load main class annotator.Main
```

**Comment by mernst** [comment]
We are replacing the infer-and-annotate.sh tool by a new implementation, so I am closing this issue.
