### ISSUE TITLE
Eclipse plugin error from comment block when running selected checkers

### ISSUE THREAD

**Issue by GoogleCodeExporter** [typetools/checker-framework#239]
```
What steps will reproduce the problem?
1. Have a source code file containing an annotated try-with-resources:

try (
/*@DefaultQualifier(Nullable.class)*/
InputStream in = resourceRoot.getResourceAsStream(url)) {
  if(in != null) {
    bytes = readFully(in, BUFFER_SIZE);
  } else {
    throw new IllegalArgumentException("Resource not found: " + url);
  }
}

2. Add characters *//* between @ and DefaultQualifier to "disable" the 
annotation so that Checker Framework would skip over it, and save.
3. Run selected checkers on the source code file.

What is the expected output? What do you see instead?

Checker should treat /*@*//*DefaultQualifier(Nullable.class)*/ as a normal 
comment and not process it.

Instead the Eclipse plugin tries to add a marker which results in an error in 
the Error Log.

What version of the product are you using? On what operating system?

Checker Framework Feature 1.6.6, Eclipse IDE for Java Developers 
2.0.0.20130613-0530, Java(TM) SE Runtime Environment 1.7.0_25-b16, Windows 8.1 
Pro Preview Evaluation copy Build 9431

Please provide any additional information below.

The Error Log shows the following:

java.lang.RuntimeException: Marker reporter expects at least 3 arguments 
separated by $$.
Message was: illegal start of type
          /*@*//*DefaultQualifier(Nullable.class)*/ line was 132
    at checkers.eclipse.marker.MarkerReporter.<init>(MarkerReporter.java:46)
    at checkers.eclipse.util.MarkerUtil.addMarker(MarkerUtil.java:61)
    at checkers.eclipse.actions.CheckerWorker.markErrors(CheckerWorker.java:144)
    at checkers.eclipse.actions.CheckerWorker.work(CheckerWorker.java:107)
    at checkers.eclipse.actions.CheckerWorker.run(CheckerWorker.java:81)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
```

Original issue reported on code.google.com by `timo.kin...@gmail.com` on 14 Aug 2013 at 2:18

**Comment by mernst** [comment]
Since the underlying crash is fixed, maybe this issue is fixed.
If it's still a problem, open a new issue.
