### ISSUE TITLE
Parameters of inherited implementations not checked for compatibility with methods they implement

### ISSUE THREAD

**Issue by cpovirk** [typetools/checker-framework#2724]
```java
import java.util.function.Consumer;
import java.util.function.Supplier;
import org.checkerframework.checker.nullness.qual.Nullable;

abstract class StringSupplier implements Supplier<String> {
  private String s = "";

  public void accept(String s) {
    this.s = s;
  }

  @Override
  public String get() {
    return s;
  }
}

class Holder extends StringSupplier implements Consumer<@Nullable String> {}

class Foo {
  public static void main(String[] args) {
    Holder h = new Holder();
    ((Consumer<@Nullable String>) h).accept(null);
    h.get().hashCode();
  }
}
```

```
$ checker/bin/javac -processor org.checkerframework.checker.nullness.NullnessChecker Foo.java && java Foo
Exception in thread "main" java.lang.NullPointerException
  at Foo.main(Foo.java:24)
```

I started down this path because I noticed that it was possible to make the same type implement, e.g., both `Consumer<String>` and `Consumer<@Nullable String>`. However, I wasn't finding a way to turn that into a `NullPointerException` (except by using a lambda, as in #2723). When I finally found the `NullPointerException` above, it turned out that I didn't need to implement `Consumer` twice to trigger it. (It does still seem a little dicey that it's possible to have a type that implements both `Consumer<String>` and `Consumer<@Nullable String>` (since Java doesn't allow implementing, say, `Consumer<String>` and `Consumer<Object>`), but that's the worst I can say about that at the moment.)

[Source file](https://github.com/typetools/checker-framework/files/3510663/Foo.java.txt) and [`-version -verbose -AprintAllQualifiers` output](https://github.com/typetools/checker-framework/files/3510662/err.txt) attached.

**Comment by cpovirk** [comment]
Update: I turned the dicey behavior into a `NullPointerException` in #2725.

**Comment by cpovirk** [comment]
You've probably noticed this already, but FYI, this also applies to return types:

```java
$ cat Caller.java 
import org.checkerframework.checker.nullness.qual.Nullable;

interface Supplier<T> {
  T get();
}

class Super {
  public @Nullable String get() {
    return null;
  }
}

class Sub extends Super implements Supplier<String> {}

class Caller {
  public static void main(String[] args) {
    Supplier<String> s = new Sub();
    s.get().toString();
  }
}
```

```
$ checker/bin/javac -processor org.checkerframework.checker.nullness.NullnessChecker -AcheckCastElementType Caller.java && java Caller
Exception in thread "main" java.lang.NullPointerException
  at Caller.main(Caller.java:18)
```

(I briefly thought that I'd hit this in real code. But now I don't think I actually did. Rather, I was just confused, partly because (a) I was mis-remembering [the code I was looking at](https://github.com/google/guava/blob/70164025a8cac6ddec8c25c721e2ad427d7d75b7/guava/src/com/google/common/collect/CollectSpliterators.java#L368) and partly because (b) it used `Spliterator.trySplit`, which doesn't ([yet](https://github.com/typetools/checker-framework/pull/3029) :)) have a `@Nullable` return type in the stub files.)

**Comment by wmdietl** [comment]
The same issue exists without using generics. Take this combined example:

```java
> cat UnsafeInterface.java
import org.checkerframework.checker.nullness.qual.Nullable;

interface Foo {
    Object foo(@Nullable String x);
}

class A {
    public @Nullable Object foo(String x) {
        x.hashCode();
        return null;
    }
}

class B extends A implements Foo {}

public class UnsafeInterface {
    static void callFoo1(Foo f) {
        f.foo(null);
    }

    static void callFoo2(Foo f) {
        f.foo("hi").hashCode();
    }

    public static void main(String[] args) {
        // Results in an NPE but no warning from the Nullness Checker.
        if (args.length == 0) {
            callFoo1(new B());
        } else {
            callFoo2(new B());
        }
    }
}
```

```
> ./checker/bin/javac -processor nullness UnsafeInterface.java

> java UnsafeInterface
Exception in thread "main" java.lang.NullPointerException
        at A.foo(UnsafeInterface.java:9)
        at UnsafeInterface.callFoo1(UnsafeInterface.java:18)
        at UnsafeInterface.main(UnsafeInterface.java:28)

> java UnsafeInterface arg
Exception in thread "main" java.lang.NullPointerException
        at UnsafeInterface.callFoo2(UnsafeInterface.java:22)
        at UnsafeInterface.main(UnsafeInterface.java:30)
```

Let me also mention #679 as related.
