### ISSUE TITLE
Types shouldn't be allowed to implement both Foo<Bar> and Foo<@Nullable Bar>

### ISSUE THREAD

**Issue by cpovirk** [typetools/checker-framework#2725]
As noted in #2724, but now I have a way to turn it into a `NullPointerException`:

```java
import java.util.function.Consumer;
import java.util.function.Supplier;
import org.checkerframework.checker.nullness.qual.Nullable;

interface SupplierOfNullable<T> extends Supplier<@Nullable T> {}

interface SupplierAndConsumer<T> extends Supplier<T>, Consumer<T> {}

class Supplumer implements SupplierAndConsumer<String>, SupplierOfNullable<String> {
  @Override
  public void accept(String s) {
    s.length();
  }

  @Override
  public String get() {
    return "";
  }
}

class Foo {
  public static void main(String[] args) {
    SupplierOfNullable<String> c = new Supplumer();
    SupplierAndConsumer<@Nullable String> s = (SupplierAndConsumer<@Nullable String>) c;
    s.accept(null);
  }
}
```

```
$ checker/bin/javac -processor org.checkerframework.checker.nullness.NullnessChecker Foo.java && java Foo
Exception in thread "main" java.lang.NullPointerException
  at Supplumer.accept(Foo.java:12)
  at Supplumer.accept(Foo.java:9)
  at Foo.main(Foo.java:25)
```

[Source file](https://github.com/typetools/checker-framework/files/3510733/Foo.java.txt) and [`-version -verbose -AprintAllQualifiers` output](https://github.com/typetools/checker-framework/files/3510732/err.txt) attached.

**Comment by smillst** [comment]
I think this is a duplicate of https://github.com/typetools/checker-framework/issues/679.

**Comment by cpovirk** [comment]
Oops, thanks.

**Comment by smillst** [comment]
Thanks for reporting though!
