### ISSUE TITLE
NCDFE com.sun.source.util.TaskListener using javac JDK8

### ISSUE THREAD

**Issue by maggu2810** [typetools/checker-framework#2824]
I would like to report a bug and provide an reproducible example the same way as I done it before...

Something seems to be changed how to use the checker-framework with javac.

I looked at the manual but did not found any useful.
After that I looked on Github found #2794

So, I changed how I used javac.

The error I got first

```
error: SourceChecker.typeProcessingStart: unexpected Throwable (NoSuchMethodError); message: com.sun.tools.javac.code.Type.stripMetadata()Lcom/sun/tools/javac/code/Type;
  Exception: java.lang.NoSuchMethodError: com.sun.tools.javac.code.Type.stripMetadata()Lcom/sun/tools/javac/code/Type;; Stack trace: org.checkerframework.javacutil.TypeAnnotationUtils.unannotatedType(TypeAnnotationUtils.java:558)
  org.checkerframework.framework.type.BoundsInitializer.initializeTypeArgs(BoundsInitializer.java:99)
  org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType.getTypeArguments(AnnotatedTypeMirror.java:899)
  org.checkerframework.framework.util.element.TypeDeclarationApplier.extractAndApply(TypeDeclarationApplier.java:111)
  org.checkerframework.framework.util.element.TypeDeclarationApplier.apply(TypeDeclarationApplier.java:20)
  org.checkerframework.framework.type.ElementAnnotationApplier.applyInternal(ElementAnnotationApplier.java:105)
  org.checkerframework.framework.type.ElementAnnotationApplier.apply(ElementAnnotationApplier.java:75)
  org.checkerframework.framework.type.AnnotatedTypeFactory.fromElement(AnnotatedTypeFactory.java:1234)
  org.checkerframework.framework.type.AnnotatedTypeFactory.fromElement(AnnotatedTypeFactory.java:2489)
  org.checkerframework.common.basetype.BaseTypeVisitor.<init>(BaseTypeVisitor.java:229)
  org.checkerframework.common.basetype.BaseTypeVisitor.<init>(BaseTypeVisitor.java:209)
  org.checkerframework.common.basetype.BaseTypeChecker.createSourceVisitor(BaseTypeChecker.java:223)
  org.checkerframework.common.basetype.BaseTypeChecker.createSourceVisitor(BaseTypeChecker.java:84)
  org.checkerframework.framework.source.SourceChecker.initChecker(SourceChecker.java:899)
  org.checkerframework.common.basetype.BaseTypeChecker.initChecker(BaseTypeChecker.java:99)
  org.checkerframework.common.basetype.BaseTypeChecker.initChecker(BaseTypeChecker.java:90)
  org.checkerframework.framework.source.SourceChecker.typeProcessingStart(SourceChecker.java:855)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:157)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  com.sun.tools.javac.main.Main.compile(Main.java:523)
  com.sun.tools.javac.main.Main.compile(Main.java:381)
  com.sun.tools.javac.main.Main.compile(Main.java:370)
  com.sun.tools.javac.main.Main.compile(Main.java:361)
  com.sun.tools.javac.Main.compile(Main.java:56)
  com.sun.tools.javac.Main.main(Main.java:42)
```

does not occur anymore.
So, a step closer...

But there is now another one:

```
An annotation processor threw an uncaught exception.
Consult the following stack trace for details.
java.lang.NoClassDefFoundError: com/sun/source/util/TaskListener
        at org.checkerframework.javacutil.AbstractTypeProcessor.<init>(AbstractTypeProcessor.java:83)
        at org.checkerframework.framework.source.SourceChecker.<init>(SourceChecker.java:338)
        at org.checkerframework.common.basetype.BaseTypeChecker.<init>(BaseTypeChecker.java:84)
        at org.checkerframework.checker.initialization.InitializationChecker.<init>(InitializationChecker.java:22)
        at org.checkerframework.checker.nullness.NullnessChecker.<init>(NullnessChecker.java:32)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$NameProcessIterator.hasNext(JavacProcessingEnvironment.java:409)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.hasNext(JavacProcessingEnvironment.java:609)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.atLeastOneProcessor(JavacProcessingEnvironment.java:447)
        at com.sun.tools.javac.main.JavaCompiler.initProcessAnnotations(JavaCompiler.java:1050)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:852)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        at com.sun.tools.javac.main.Main.compile(Main.java:381)
        at com.sun.tools.javac.main.Main.compile(Main.java:370)
        at com.sun.tools.javac.main.Main.compile(Main.java:361)
        at com.sun.tools.javac.Main.compile(Main.java:56)
        at com.sun.tools.javac.Main.main(Main.java:42)
```

I called javac this way:

```sh
CF_VER=2.11.1

javac \
    \
    -d out \
    src/Test.java \
    -version \
    -verbose \
    -AprintAllQualifiers \
    -g \
    -encoding UTF-8 \
    -AshowSuppressWarningKeys \
    \
    -J-Xbootclasspath/p:../checkerframework/javacutil-"${CF_VER}".jar \
    -Xbootclasspath/p:../checkerframework/jdk8-"${CF_VER}".jar \
    -cp ../checkerframework/checker-qual-"${CF_VER}".jar \
    -processorpath ../checkerframework/checker-"${CF_VER}".jar \
    -processor org.checkerframework.checker.nullness.NullnessChecker \
    -source 8 -target 8
```

In the merged documentation PR you used "javac" for `-J-Xbootclasspath/p`.
Is it correct to use the `javacutil` artifact? I did not found a `javac` artifact on Maven Central.

The whole example can be found here: https://github.com/maggu2810/checker-framework-demo/commit/3f763045495fa9ee1a5344750c929c4b3ac6566a#diff-5849842bd9f319f1a8a800ef326c65d5 (I assume the error I would like to demonstrate with that example fits to #1345 -- but that's another story, if the error can be demonstrated at all.)

**Comment by smillst** [comment]
Sorry you're having trouble. The manual will be updated during the next release, Nov. 1st.

If you are using Maven Central, then you need to use the Error Prone javac.jar.  
https://search.maven.org/artifact/com.google.errorprone/javac/9%2B181-r4173-1/jar
(This is mentioned at the top of the new section in that pull request, but it was probably hard to see in the tex file.)

**Comment by maggu2810** [comment]
Thank you for your answer and sorry for not reading the instructions correctly.
After ssing the Error Prone javac the demo works as expected.
