### ISSUE TITLE
"AsSuperVisitor: type is not an erased subtype of supertype" errors on many casts with -AcheckCastElementType

### ISSUE THREAD

**Issue by cpovirk** [typetools/checker-framework#3028]
When I experimented with turning on `-AcheckCastElementType`, I discovered that it produces crashes on many casts. For example:

```java
$ cat Cast.java 
class Cast {
  void cast(Object o) {
    Cast cast = (Cast) o;
  }
}
```

```
$ checker/bin/javac -processor org.checkerframework.checker.nullness.NullnessChecker -AcheckCastElementType Cast.java 
error: AsSuperVisitor: type is not an erased subtype of supertype.
  type: @Initialized @NonNull Object
  superType: @Initialized @NonNull Cast
  Compilation unit: Cast.java
  Last visited tree at line 3 column 17:
      Cast cast = (Cast) o;
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.javacutil.BugInCF.<init>(BugInCF.java:25)
  org.checkerframework.framework.type.AsSuperVisitor.errorTypeNotErasedSubtypeOfSuperType(AsSuperVisitor.java:154)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:338)
  org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:28)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:307)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:57)
  org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:85)
  org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:67)
  org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:112)
  org.checkerframework.framework.util.AnnotatedTypes.castedAsSuper(AnnotatedTypes.java:140)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:465)
  org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:41)
  org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:307)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:182)
  org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:158)
  org.checkerframework.common.basetype.BaseTypeVisitor.isTypeCastSafe(BaseTypeVisitor.java:1926)
  org.checkerframework.common.basetype.BaseTypeVisitor.checkTypecastSafety(BaseTypeVisitor.java:1879)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitTypeCast(BaseTypeVisitor.java:1985)
  org.checkerframework.checker.initialization.InitializationVisitor.visitTypeCast(InitializationVisitor.java:270)
  org.checkerframework.checker.nullness.NullnessVisitor.visitTypeCast(NullnessVisitor.java:428)
  org.checkerframework.checker.nullness.NullnessVisitor.visitTypeCast(NullnessVisitor.java:54)
  com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:2022)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:88)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:301)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:167)
  com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  com.sun.source.util.TreeScanner.visitVariable(TreeScanner.java:223)
  org.checkerframework.framework.source.SourceVisitor.visitVariable(SourceVisitor.java:100)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitVariable(BaseTypeVisitor.java:1043)
  org.checkerframework.checker.initialization.InitializationVisitor.visitVariable(InitializationVisitor.java:167)
  org.checkerframework.checker.initialization.InitializationVisitor.visitVariable(InitializationVisitor.java:52)
  com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:968)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:88)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:301)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:167)
  com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
  com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:88)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:301)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:167)
  com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:206)
  org.checkerframework.framework.source.SourceVisitor.visitMethod(SourceVisitor.java:106)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitMethod(BaseTypeVisitor.java:683)
  org.checkerframework.checker.initialization.InitializationVisitor.visitMethod(InitializationVisitor.java:337)
  org.checkerframework.checker.initialization.InitializationVisitor.visitMethod(InitializationVisitor.java:52)
  com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:88)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:301)
  org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:167)
  com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
  org.checkerframework.framework.source.SourceVisitor.visitClass(SourceVisitor.java:94)
  org.checkerframework.common.basetype.BaseTypeVisitor.processClassTree(BaseTypeVisitor.java:384)
  org.checkerframework.checker.initialization.InitializationVisitor.processClassTree(InitializationVisitor.java:295)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:339)
  org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:167)
  com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
  org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:82)
  org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:1020)
  org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:523)
  org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:182)
  com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:828)
  com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1404)
  com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1363)
  com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:959)
  com.sun.tools.javac.main.Main.compile(Main.java:302)
  com.sun.tools.javac.main.Main.compile(Main.java:162)
  com.sun.tools.javac.Main.compile(Main.java:57)
  com.sun.tools.javac.Main.main(Main.java:43)
1 error
```

[Source file](https://github.com/typetools/checker-framework/files/4017075/Cast.java.txt) and [`-version -verbose -AprintAllQualifiers` output](https://github.com/typetools/checker-framework/files/4017074/err.txt) attached.

**Comment by cpovirk** [comment]
Here's a different `BugInCF` from `-AcheckCastElementType`, this one specific to primitives:

```java
checker-framework-3.7.1 $ cat ~/code/CastToPrimitive.java
class CastToPrimitive {
  int x(Object o) {
    return (int) o;
  }
}

checker-framework-3.7.1 $ checker/bin/javac -processor org.checkerframework.checker.nullness.NullnessChecker -AcheckCastElementType ~/code/CastToPrimitive.java 
error: AsSuperVisitor Declared_Primitive: type is not a box primitive.
  ; The Checker Framework crashed.  Please report the crash.
  Compilation unit: /usr/local/google/home/cpovirk/code/CastToPrimitive.java
  Last visited tree at line 3 column 12:
      return (int) o;
  Exception: java.lang.Throwable; java.lang.Throwable
        at org.checkerframework.javacutil.BugInCF.<init>(BugInCF.java:16)
        at org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Primitive(AsSuperVisitor.java:364)
        at org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Primitive(AsSuperVisitor.java:29)
        at org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:338)
        at org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:65)
        at org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:96)
        at org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:78)
        at org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:112)
        at org.checkerframework.framework.util.AnnotatedTypes.castedAsSuper(AnnotatedTypes.java:140)
        at org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Primitive(DefaultTypeHierarchy.java:588)
        at org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Primitive(DefaultTypeHierarchy.java:43)
        at org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:338)
        at org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:185)
        at org.checkerframework.checker.nullness.KeyForAnnotatedTypeFactory$KeyForTypeHierarchy.isSubtype(KeyForAnnotatedTypeFactory.java:146)
        at org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:161)
        at org.checkerframework.common.basetype.BaseTypeVisitor.isTypeCastSafe(BaseTypeVisitor.java:2168)
        at org.checkerframework.common.basetype.BaseTypeVisitor.checkTypecastSafety(BaseTypeVisitor.java:2117)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitTypeCast(BaseTypeVisitor.java:2250)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitTypeCast(BaseTypeVisitor.java:175)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:2028)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:88)
        at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:303)
        at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:175)
        at jdk.compiler/com.sun.source.util.TreeScanner.visitReturn(TreeScanner.java:469)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitReturn(BaseTypeVisitor.java:1893)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitReturn(BaseTypeVisitor.java:175)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1554)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:88)
        at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:303)
        at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:175)
        at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
        at jdk.compiler/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1032)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:88)
        at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:303)
        at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:175)
        at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
        at jdk.compiler/com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:206)
        at org.checkerframework.framework.source.SourceVisitor.visitMethod(SourceVisitor.java:106)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitMethod(BaseTypeVisitor.java:750)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitMethod(BaseTypeVisitor.java:175)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:88)
        at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:303)
        at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:175)
        at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
        at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
        at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
        at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
        at org.checkerframework.framework.source.SourceVisitor.visitClass(SourceVisitor.java:94)
        at org.checkerframework.common.basetype.BaseTypeVisitor.processClassTree(BaseTypeVisitor.java:388)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:341)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:175)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
        at org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:82)
        at org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:916)
        at org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:503)
        at org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:496)
        at org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:190)
        at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:828)
        at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1394)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1351)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:947)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
        at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
... snip similar error for InitializationVisitor ...
```

**Comment by cpovirk** [comment]
(Certainly feel free to split off a new issue if you want. I figured that `-AcheckCastElementType` probably doesn't justify a lot of attention, so it would be more useful to collect the possible problems with it in one place. (I guess I will retitle this one.) I, for one, have no evidence that it is actually important to enable in any of my projects; I have just been experimenting :))
