### ISSUE TITLE
Crash when creating array with type parameter

### ISSUE THREAD

**Issue by jwaataja** [typetools/checker-framework#3277]
Similar error to [this issue](https://github.com/typetools/checker-framework/issues/3021).

I get a crash when instantiating arrays that have a `?` type parameter and an annotation.
```java
import org.checkerframework.checker.tainting.qual.*;

public class C {
    public static void f() {
        Object o = new @Tainted Generic<?>[0];
    }
}

class Generic<T> {
}
```
```
javac -processor TaintingChecker C.java
error: handleInvalid(this=org.checkerframework.framework.util.element.MethodApplier):
  Invalid variable and element passed to extractAndApply; type: void f()
    element: f() (kind: METHOD), invalid annotations: @org.checkerframework.checker.tainting.qual.Tainted ([UNKNOWN, position UNKNOWN!, pos = -1])
  Targeted annotations: METHOD_RECEIVER, METHOD_RETURN, THROWS
  Valid annotations: LOCAL_VARIABLE, RESOURCE_VARIABLE, EXCEPTION_PARAMETER, NEW, CAST, INSTANCEOF, METHOD_INVOCATION_TYPE_ARGUMENT, CONSTRUCTOR_INVOCATION_TYPE_ARGUMENT, METHOD_REFERENCE, CONSTRUCTOR_REFERENCE, METHOD_REFERENCE_TYPE_ARGUMENT, CONSTRUCTOR_REFERENCE_TYPE_ARGUMENT, METHOD_TYPE_PARAMETER, METHOD_TYPE_PARAMETER_BOUND, METHOD_FORMAL_PARAMETER, CLASS_EXTENDS
  ; The Checker Framework crashed.  Please report the crash.
  Compilation unit: C.java
  Last visited tree at line 4 column 5:
      public static void f() {
  Exception: java.lang.Throwable; java.lang.Throwable
  	at org.checkerframework.javacutil.BugInCF.<init>(BugInCF.java:14)
  	at org.checkerframework.framework.util.element.TargetedElementAnnotationApplier.handleInvalid(TargetedElementAnnotationApplier.java:140)
  	at org.checkerframework.framework.util.element.TargetedElementAnnotationApplier.extractAndApply(TargetedElementAnnotationApplier.java:204)
  	at org.checkerframework.framework.util.element.MethodApplier.extractAndApply(MethodApplier.java:127)
  	at org.checkerframework.framework.util.element.MethodApplier.apply(MethodApplier.java:33)
  	at org.checkerframework.framework.type.ElementAnnotationApplier.applyInternal(ElementAnnotationApplier.java:129)
  	at org.checkerframework.framework.type.ElementAnnotationApplier.apply(ElementAnnotationApplier.java:78)
  	at org.checkerframework.framework.type.TypeFromMemberVisitor.visitMethod(TypeFromMemberVisitor.java:79)
  	at org.checkerframework.framework.type.TypeFromMemberVisitor.visitMethod(TypeFromMemberVisitor.java:24)
  	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
  	at com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:80)
  	at org.checkerframework.framework.type.TypeFromTree.fromMember(TypeFromTree.java:50)
  	at org.checkerframework.framework.type.AnnotatedTypeFactory.fromMember(AnnotatedTypeFactory.java:1226)
  	at org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:1029)
  	at org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:2442)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.visitMethod(BaseTypeVisitor.java:560)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.visitMethod(BaseTypeVisitor.java:165)
  	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:88)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:294)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:165)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
  	at org.checkerframework.framework.source.SourceVisitor.visitClass(SourceVisitor.java:94)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.processClassTree(BaseTypeVisitor.java:377)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:332)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:165)
  	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
  	at org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:82)
  	at org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:868)
  	at org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:510)
  	at org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:190)
  	at com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:828)
  	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1404)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1363)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:959)
  	at com.sun.tools.javac.main.Main.compile(Main.java:302)
  	at com.sun.tools.javac.main.Main.compile(Main.java:162)
  	at com.sun.tools.javac.Main.compile(Main.java:57)
  	at com.sun.tools.javac.Main.main(Main.java:43)
```
[Source file](https://github.com/typetools/checker-framework/files/4537788/C.java.txt)
[Error output with debug info](https://github.com/typetools/checker-framework/files/4537797/error.txt)

**Comment by wmdietl** [comment]
Thanks for reporting this issue!

Unfortunately, this bug is much more serious than the previous #3021.

Normal javac produces a `ClassWriter: Position UNKNOWN in type annotation` warning for this example. That's bad.

If I put the code into a field, the compiler crashes with an AssertionError. That's really bad.

In #3330 I work around the problem within method bodies. I need to look through the javac bug database and see whether there is an issue filed for this already.
Even with a fix in javac, we will need to work around the problem until everyone uses a javac with that fix.

For uses within fields, the only work-around for now is to use a helper method to produce the value.

**Comment by wmdietl** [comment]
I found a JDK bug and commented about the crash: https://bugs.openjdk.java.net/browse/JDK-8233945
