### ISSUE TITLE
Nullness checker permits dereference of <T extends @Nullable Foo & @Nullable Bar>

### ISSUE THREAD

**Issue by cpovirk** [typetools/checker-framework#3380]
First: As expected, the checker will _not_ let me assign a value of type `T` (where `<T extends @Nullable Foo & @Nullable Bar>`) to a variable of explicit type `@NonNull Object`. (I saw https://github.com/typetools/checker-framework/issues/3349; this is a simpler case, so it's not affected by that issue.) Also as expected, it will _not_ let me return a `T` from a method that declares the return type `Object`.

However, it _will_ let me _dereference_ a `T`. This can permit NPE.

I didn't encounter this is "real" code, just while playing around.

```java
$ cat CfIntersection.java
import org.checkerframework.checker.nullness.qual.Nullable;

class CfIntersection {
  static <T extends @Nullable Object & @Nullable Foo> void go(T t) {
    t.toString();
  }

  public static void main(String[] args) {
    go(null);
  }
}

interface Foo {}

$ checker/bin/javac -processor org.checkerframework.checker.nullness.NullnessChecker -version -verbose -AprintAllQualifiers CfIntersection.java
javac (version info not available)
...
Round 1:
        input files: {CfIntersection, Foo}
        annotations: []
        last round: false
Processor org.checkerframework.checker.nullness.NullnessChecker matches [] and returns false.
Round 2:
        input files: {}
        annotations: []
        last round: true
[checking CfIntersection]
...
[checking Foo]
...

$ java CfIntersection
Exception in thread "main" java.lang.NullPointerException
        at CfIntersection.go(CfIntersection.java:5)
        at CfIntersection.main(CfIntersection.java:9)
```

**Comment by cpovirk** [comment]
This is with CF 3.4.1.

**Comment by cpovirk** [comment]
Sorry, bad searching on my part: This is already filed as #868.
