### ISSUE TITLE
Crash report: @Nullable KV<? extends byte @Nullable [], ? extends byte @Nullable []>

### ISSUE THREAD

**Issue by kennknowles** [typetools/checker-framework#3496]
This occurred after I made an edit to introduce covariance: from `@Nullable KV<byte @Nullable [], byte @Nullable []>` to `@Nullable KV<? extends byte @Nullable [], ? extends byte @Nullable []` on line 123 of `NativeFileSorter.java`.

Steps to reproduce:

```
git clone --single-branch --branch checker-crash-report http://github.com/kennknowles/beam.git
cd beam
./gradlew :sdks:java:extensions:sorter:compileJava
```

Resulting output:

```
Configuration on demand is an incubating feature.

> Task :sdks:java:extensions:sorter:compileJava
/Users/klk/GitHub/apache/beam/sdks/java/extensions/sorter/src/main/java/org/apache/beam/sdk/extensions/sorter/NativeFileSorter.java:133: error: no suitable method found for add(KV<CAP#1,CAP#2>)
          tempList.add(kv);
                  ^
    method Collection.add(KV<byte[],byte[]>) is not applicable
      (argument mismatch; KV<CAP#1,CAP#2> cannot be converted to KV<byte[],byte[]>)
    method List.add(KV<byte[],byte[]>) is not applicable
      (argument mismatch; KV<CAP#1,CAP#2> cannot be converted to KV<byte[],byte[]>)
  where CAP#1,CAP#2 are fresh type-variables:
    CAP#1 extends byte @org.checkerframework.checker.nullness.qual.Nullable [] from capture of ? extends byte @org.checkerframework.checker.nullness.qual.Nullable []
    CAP#2 extends byte @org.checkerframework.checker.nullness.qual.Nullable [] from capture of ? extends byte @org.checkerframework.checker.nullness.qual.Nullable []
/Users/klk/GitHub/apache/beam/sdks/java/extensions/sorter/src/main/java/org/apache/beam/sdk/extensions/sorter/NativeFileSorter.java:134: error: incompatible types: KV<CAP#1,CAP#2> cannot be converted to KV<byte[],byte[]>
          currentBlockSize += estimateSizeOf(kv);
                                             ^
  where CAP#1,CAP#2 are fresh type-variables:
    CAP#1 extends byte @org.checkerframework.checker.nullness.qual.Nullable [] from capture of ? extends byte @org.checkerframework.checker.nullness.qual.Nullable []
    CAP#2 extends byte @org.checkerframework.checker.nullness.qual.Nullable [] from capture of ? extends byte @org.checkerframework.checker.nullness.qual.Nullable []
error: SourceChecker.typeProcess: unexpected Throwable (IllegalArgumentException) while processing /Users/klk/GitHub/apache/beam/sdks/java/extensions/sorter/src/main/java/org/apache/beam/sdk/extensions/sorter/NativeFileSorter.java; message: Not a primitive type: NONE
  ; The Checker Framework crashed.  Please report the crash.
  Compilation unit: /Users/klk/GitHub/apache/beam/sdks/java/extensions/sorter/src/main/java/org/apache/beam/sdk/extensions/sorter/NativeFileSorter.java
  Last visited tree at line 50 column 1:
  class NativeFileSorter {
  Exception: java.lang.IllegalArgumentException: Not a primitive type: NONE; java.lang.IllegalArgumentException: Not a primitive type: NONE
        at com.sun.tools.javac.model.JavacTypes.getPrimitiveType(JavacTypes.java:170)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.binaryPromotedType(CFGBuilder.java:2164)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitCompoundAssignment(CFGBuilder.java:2958)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitCompoundAssignment(CFGBuilder.java:1514)
        at com.sun.tools.javac.tree.JCTree$JCAssignOp.accept(JCTree.java:1930)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitExpressionStatement(CFGBuilder.java:3619)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitExpressionStatement(CFGBuilder.java:1514)
        at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1454)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:3364)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:1514)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitWhileLoop(CFGBuilder.java:4933)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitWhileLoop(CFGBuilder.java:1514)
        at com.sun.tools.javac.tree.JCTree$JCWhileLoop.accept(JCTree.java:1086)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:3364)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:1514)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitWhileLoop(CFGBuilder.java:4933)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitWhileLoop(CFGBuilder.java:1514)
        at com.sun.tools.javac.tree.JCTree$JCWhileLoop.accept(JCTree.java:1086)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:3364)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:1514)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitTry(CFGBuilder.java:4405)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitTry(CFGBuilder.java:1514)
        at com.sun.tools.javac.tree.JCTree$JCTry.accept(JCTree.java:1322)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:3364)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:1514)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.process(CFGBuilder.java:1669)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.process(CFGBuilder.java:1713)
        at org.checkerframework.framework.flow.CFCFGBuilder.build(CFCFGBuilder.java:60)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1234)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:1161)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1551)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:258)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:307)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:165)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
        at org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:82)
        at org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:894)
        at org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:510)
        at org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:503)
        at org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:190)
        at com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:828)
        at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
        at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1404)
        at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1353)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
        at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
        at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
        at org.gradle.api.internal.tasks.compile.AnnotationProcessingCompileTask.call(AnnotationProcessingCompileTask.java:92)
        at org.gradle.api.internal.tasks.compile.ResourceCleaningCompilationTask.call(ResourceCleaningCompilationTask.java:57)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:50)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:36)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:86)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:74)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:42)
        at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:111)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
error: SourceChecker.typeProcess: unexpected Throwable (IllegalArgumentException) while processing /Users/klk/GitHub/apache/beam/sdks/java/extensions/sorter/src/main/java/org/apache/beam/sdk/extensions/sorter/NativeFileSorter.java; message: Not a primitive type: NONE
  ; The Checker Framework crashed.  Please report the crash.
  Compilation unit: /Users/klk/GitHub/apache/beam/sdks/java/extensions/sorter/src/main/java/org/apache/beam/sdk/extensions/sorter/NativeFileSorter.java
  Last visited tree at line 50 column 1:
  class NativeFileSorter {
  Exception: java.lang.IllegalArgumentException: Not a primitive type: NONE; java.lang.IllegalArgumentException: Not a primitive type: NONE
        at com.sun.tools.javac.model.JavacTypes.getPrimitiveType(JavacTypes.java:170)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.binaryPromotedType(CFGBuilder.java:2164)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitCompoundAssignment(CFGBuilder.java:2958)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitCompoundAssignment(CFGBuilder.java:1514)
        at com.sun.tools.javac.tree.JCTree$JCAssignOp.accept(JCTree.java:1930)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitExpressionStatement(CFGBuilder.java:3619)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitExpressionStatement(CFGBuilder.java:1514)
        at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1454)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:3364)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:1514)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitWhileLoop(CFGBuilder.java:4933)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitWhileLoop(CFGBuilder.java:1514)
        at com.sun.tools.javac.tree.JCTree$JCWhileLoop.accept(JCTree.java:1086)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:3364)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:1514)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitWhileLoop(CFGBuilder.java:4933)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitWhileLoop(CFGBuilder.java:1514)
        at com.sun.tools.javac.tree.JCTree$JCWhileLoop.accept(JCTree.java:1086)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:3364)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:1514)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitTry(CFGBuilder.java:4405)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitTry(CFGBuilder.java:1514)
        at com.sun.tools.javac.tree.JCTree$JCTry.accept(JCTree.java:1322)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:3364)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:1514)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.process(CFGBuilder.java:1669)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.process(CFGBuilder.java:1713)
        at org.checkerframework.framework.flow.CFCFGBuilder.build(CFCFGBuilder.java:60)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1234)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:1161)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:1551)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:258)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:307)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:165)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
        at org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:82)
        at org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:894)
        at org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:510)
        at org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:190)
        at com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:828)
        at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
        at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1404)
        at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1353)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
        at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
        at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
        at org.gradle.api.internal.tasks.compile.AnnotationProcessingCompileTask.call(AnnotationProcessingCompileTask.java:92)
        at org.gradle.api.internal.tasks.compile.ResourceCleaningCompilationTask.call(ResourceCleaningCompilationTask.java:57)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:50)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:36)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:86)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:74)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:42)
        at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:111)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
/Users/klk/GitHub/apache/beam/sdks/java/extensions/sorter/src/main/java/org/apache/beam/sdk/extensions/sorter/HadoopExternalSorter.java:90: error: [initialization.fields.uninitialized] the constructor does not initialize fields: writer, sorter, tempDir, paths
  private HadoopExternalSorter(Options options) {
          ^
/Users/klk/GitHub/apache/beam/sdks/java/extensions/sorter/src/main/java/org/apache/beam/sdk/extensions/sorter/HadoopExternalSorter.java:152: error: [assignment.type.incompatible] incompatible types in assignment.
      nextKV = KV.of(null, null); // A dummy value that will be overwritten by next().
                    ^
  found   : @Initialized @NonNull KV<@Initialized @NonNull byte @Initialized @Nullable [], @Initialized @NonNull byte @Initialized @Nullable []>
  required: @Initialized @NonNull KV<@Initialized @NonNull byte @Initialized @NonNull [], @Initialized @NonNull byte @Initialized @NonNull []>
/Users/klk/GitHub/apache/beam/sdks/java/extensions/sorter/src/main/java/org/apache/beam/sdk/extensions/sorter/HadoopExternalSorter.java:153: error: [method.invocation.invalid] call to next() not allowed on the given receiver.
      next();
          ^
  found   : @Initialized @NonNull HadoopExternalSorter.@UnderInitialization(org.apache.beam.sdk.extensions.sorter.HadoopExternalSorter.SortedRecordsIterator.class) @NonNull SortedRecordsIterator
  required: @Initialized @NonNull HadoopExternalSorter.@Initialized @NonNull SortedRecordsIterator
/Users/klk/GitHub/apache/beam/sdks/java/extensions/sorter/src/main/java/org/apache/beam/sdk/extensions/sorter/HadoopExternalSorter.java:185: error: [assignment.type.incompatible] incompatible types in assignment.
          nextKV = null;
                   ^
  found   : null
  required: @Initialized @NonNull KV<@Initialized @NonNull byte @Initialized @NonNull [], @Initialized @NonNull byte @Initialized @NonNull []>
/Users/klk/GitHub/apache/beam/sdks/java/extensions/sorter/src/main/java/org/apache/beam/sdk/extensions/sorter/InMemorySorter.java:153: error: [argument.type.incompatible] incompatible types in argument.
      return Long.parseLong(bitsPerWord) / 8;
                            ^
  found   : @Initialized @Nullable String
  required: @Initialized @NonNull String
/Users/klk/GitHub/apache/beam/sdks/java/extensions/sorter/src/main/java/org/apache/beam/sdk/extensions/sorter/BufferedExternalSorter.java:140: error: [assignment.type.incompatible] incompatible types in assignment.
    inMemorySorter = null;
                     ^
  found   : null
  required: @Initialized @NonNull InMemorySorter
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
10 errors

> Task :sdks:java:extensions:sorter:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sdks:java:extensions:sorter:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.2.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 6s
44 actionable tasks: 1 executed, 43 up-to-date
```

**Comment by wmdietl** [comment]
Thanks for the bug reports!
Like for #3499, there already is a javac error before the CF crash. The CF shouldn't run at all if there is a javac error, so it's unclear why we even get into this state.
The unexpected type is a result of the javac error, so it doesn't seem worth trying to work around that.
However, it would be good to understand why we reach this state and stop more gracefully.

**Comment by smillst** [comment]
Closing in favor of https://github.com/typetools/checker-framework/issues/4041.
