### ISSUE TITLE
ClassCastException in AnnotatedTypeMirror$AnnotatedIntersectionType.directSuperTypes

### ISSUE THREAD

**Issue by msridhar** [typetools/checker-framework#3569]
Input (reduced from code in https://github.com/h2oai/h2o-3):
```java
import java.io.Serializable;
import java.util.Map;

class ClassCastCrash {
    static class AutoBuffer {
        public <T extends Freezable> T get() {
            return null;
        }

        public String getStr() {
            return "hi";
        }
    }

    public interface Freezable<T extends Freezable> extends Cloneable {}

    public abstract static class Iced<D extends Iced>
            implements Freezable<D>, java.io.Externalizable {
        @Override
        public void readExternal(java.io.ObjectInput ois)
                throws java.io.IOException, ClassNotFoundException {}

        @Override
        public void writeExternal(java.io.ObjectOutput oos) throws java.io.IOException {}
    }

    public abstract static class IcedHashMapBase<K, V> extends Iced
            implements Map<K, V>, Cloneable, Serializable {
        public enum KeyType {
            String(String.class),
            Freezable(Freezable.class),
            ;
            Class _clazz;

            KeyType(Class clazz) {
                _clazz = clazz;
            }
        }

        @SuppressWarnings("unchecked")
        protected K readKey(AutoBuffer ab, KeyType keyType) {
            switch (keyType) {
                case String:
                    return (K) ab.getStr();
                case Freezable:
                    return ab.get();
                default:
                    return null;
            }
        }
    }
}
```
I get a crash with the tainting checker:
```
$ ./checker/bin/javac -processor TaintingChecker checker/tests/tainting/ClassCastCrash.java
error: SourceChecker.typeProcess: unexpected Throwable (ClassCastException) while processing checker/tests/tainting/ClassCastCrash.java; message: org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedTypeVariable cannot be cast to org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType
  ; The Checker Framework crashed.  Please report the crash.
  Compilation unit: checker/tests/tainting/ClassCastCrash.java
  Last visited tree at line 4 column 1:
  class ClassCastCrash {
  Exception: java.lang.ClassCastException: org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedTypeVariable cannot be cast to org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType; java.lang.ClassCastException: org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedTypeVariable cannot be cast to org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType
  	at org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedIntersectionType.directSuperTypes(AnnotatedTypeMirror.java:2075)
  	at org.checkerframework.framework.type.visitor.AnnotatedTypeScanner.visitIntersection(AnnotatedTypeScanner.java:282)
  	at org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedIntersectionType.accept(AnnotatedTypeMirror.java:2033)
  	at org.checkerframework.framework.type.visitor.AnnotatedTypeScanner.scan(AnnotatedTypeScanner.java:198)
  	at org.checkerframework.framework.type.visitor.AnnotatedTypeScanner.visitWildcard(AnnotatedTypeScanner.java:350)
  	at org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedWildcardType.accept(AnnotatedTypeMirror.java:1940)
  	at org.checkerframework.framework.type.visitor.AnnotatedTypeScanner.scan(AnnotatedTypeScanner.java:198)
  	at org.checkerframework.framework.type.visitor.AnnotatedTypeScanner.visit(AnnotatedTypeScanner.java:186)
  	at org.checkerframework.framework.type.visitor.AnnotatedTypeScanner.visit(AnnotatedTypeScanner.java:173)
  	at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.addAnnotationsFromDefaultForType(GenericAnnotatedTypeFactory.java:2008)
  	at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.addDefaultAnnotations(GenericAnnotatedTypeFactory.java:1542)
...
```

The crash occurs during a call to `AnnotatedTypeFactory.getAnnotatedType()` to get the type of the `ab.get()` call.

**Comment by smillst** [comment]
Here's a simplified test case:
```
public class Issue3569 {
    public interface MyInterface {}

    public <T extends MyInterface> T getT() {
        return null;
    }

    @SuppressWarnings("unchecked")
    protected <K> K getK(Issue3569 ab) {
        // The line below issues the following warning:
        // Unchecked assignment: 'Issue3569.MyInterface & K' to 'K'
        return ab.getT();
    }
}
```

The problem is that the Checker Framework assumes that an intersection can't have a TypeVariable as a bound, but apparently it can in some cases.
