### ISSUE TITLE
 In a raw type, all method signatures are erased -- even the method's own type parameters.

### ISSUE THREAD

**Issue by cushon** [typetools/checker-framework#3785]
```java
import org.checkerframework.checker.nullness.qual.NonNull;

class A<L> {}

abstract class B<O extends C.D> implements E<O> {
  abstract <L> A<L> g(@NonNull L l);
}

interface E<O extends C.D> {}

class C<O extends C.D> {
  interface D {}
}

class T {

  void f(B b) {
    A<Void> a = b.g(new Object());
  }
}
```

```
./checker-framework-3.7.0/checker/bin/javac -processor Nullness P.java
error: AsSuperVisitor: type is not an erased subtype of supertype.
  type: Object
  superType: Void
  ; The Checker Framework crashed.  Please report the crash.
  Compilation unit: P.java
  Last visited tree at line 18 column 17:
      A<Void> a = b.g(new Object());
  Exception: java.lang.Throwable; java.lang.Throwable
        at org.checkerframework.javacutil.BugInCF.<init>(BugInCF.java:27)
        at org.checkerframework.framework.type.AsSuperVisitor.errorTypeNotErasedSubtypeOfSuperType(AsSuperVisitor.java:165)
        at org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:349)
        at org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:29)
        at org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:314)
        at org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:65)
        at org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:96)
        at org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:78)
        at org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:112)
        at org.checkerframework.framework.util.AnnotatedTypes.castedAsSuper(AnnotatedTypes.java:140)
        at org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:504)
        at org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:43)
```

**Comment by smillst** [comment]
Here's a small test case.
```
public abstract class Issue3785<T> {
    abstract <L> void method(L l);
    @SuppressWarnings("unchecked")
    void use(Issue3785 p, Object o) {
        p.<Void>method(o);
    }
}
```

**Comment by mernst** [comment]
Thanks for the bug report!  We really appreciate it.

Looking at the [smaller test case](https://github.com/typetools/checker-framework/issues/3785#issuecomment-710682026), the call `p.<Void>method(o);` looks illegal to me.  That is, I wonder if the code illustrates a bug of the javac compiler, an infelicity in the Java Language Specification, or good Java style.  Do you have insight into that question?  That is, can you either make an argument that the call is sensible, or explain why Java permits that code?

**Comment by cushon** [comment]
My understanding is that because `p` in `p.<Void>method(o);` is raw, this is an unchecked invocation, and the signature of the method is erased from `method(L)V` to `method(Object)V`.

JLS 15.12.2.6 is at least related, but doesn't seem to speak directly to the connection between the receiver type being raw and unchecked invocation, or the effect on the parameter types (vs. the return or thrown exception types?).

**Comment by mernst** [comment]
I think the relevant text is in [Section 4.8, "Raw Types"](https://docs.oracle.com/javase/specs/jls/se11/html/jls-4.html#jls-4.8).

It states that in a raw type, all method signatures are erased -- even the method's own type parameters.

> The type of a constructor (§8.8), instance method (§8.4, §9.4), or non-static field
> (§8.3) of a raw type C that is not inherited from its superclasses or superinterfaces
> is the raw type that corresponds to the erasure of its type in the generic declaration
> corresponding to C.

(In the above, the "type of a constructor or instance method" means its signature and thrown exception types.)

This suggests that the Checker Framework should forget more type information when a receiver is raw.

**Comment by smillst** [comment]
Fixed via https://github.com/typetools/checker-framework/pull/5725.
