### ISSUE TITLE
Crash with error: AsSuperVisitor: type is not an erased subtype of supertype

### ISSUE THREAD

**Issue by msridhar** [typetools/checker-framework#3826]
Reduced from [here](https://github.com/apache/hadoop/blob/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/io/MapFile.java).  Input:
```java
public class MapFile {
  public static interface Option extends SequenceFile.Writer.Option { }
  public static class Writer {
    public static interface Option extends SequenceFile.Writer.Option { }
    private static class KeyClassOption extends Options.ClassOption
      implements Option {
      KeyClassOption(Class<?> value) {
        super(value);
      }
    }
    public Writer(SequenceFile.Writer.Option... opts) {
      Options.getOption(KeyClassOption.class, opts);
    }
  }
  public static class Options {
    public static <base, T extends base> T getOption(Class<T> cls, base [] opts) {
      return null;
    }

    public static abstract class ClassOption {
      protected ClassOption(Class<?> value)              {}
    }
        
  }
  public static class SequenceFile {
    public static class Writer {
      public static interface Option {
      }
    }
  }
}
```
Result when running tainting checker:
```
$ /Users/msridhar/git-repos/checker-framework/checker/bin/javac -processor TaintingChecker MapFile.java
error: AsSuperVisitor: type is not an erased subtype of supertype.
  type: @Tainted Option
  superType: @Tainted KeyClassOption
  ; The Checker Framework crashed.  Please report the crash.
  Compilation unit: MapFile.java
  Last visited tree at line 13 column 25:
        Options.getOption(KeyClassOption.class, opts);
  Exception: java.lang.Throwable; java.lang.Throwable
  	at org.checkerframework.javacutil.BugInCF.<init>(BugInCF.java:27)
  	at org.checkerframework.framework.type.AsSuperVisitor.errorTypeNotErasedSubtypeOfSuperType(AsSuperVisitor.java:147)
  	at org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:340)
  	at org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:29)
  	at org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:314)
  	at org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:65)
  	at org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:96)
  	at org.checkerframework.framework.type.AsSuperVisitor.asSuper(AsSuperVisitor.java:78)
  	at org.checkerframework.framework.util.AnnotatedTypes.asSuper(AnnotatedTypes.java:112)
  	at org.checkerframework.framework.util.AnnotatedTypes.castedAsSuper(AnnotatedTypes.java:140)
  	at org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:504)
  	at org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:43)
  	at org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:314)
  	at org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:185)
  	at org.checkerframework.framework.type.DefaultTypeHierarchy.visitArray_Array(DefaultTypeHierarchy.java:449)
  	at org.checkerframework.framework.type.DefaultTypeHierarchy.visitArray_Array(DefaultTypeHierarchy.java:43)
  	at org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:268)
  	at org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:185)
  	at org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:161)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.commonAssignmentCheck(BaseTypeVisitor.java:2652)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.commonAssignmentCheck(BaseTypeVisitor.java:2629)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.checkArguments(BaseTypeVisitor.java:3193)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.visitMethodInvocation(BaseTypeVisitor.java:1468)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.visitMethodInvocation(BaseTypeVisitor.java:175)
```

**Comment by smillst** [comment]
The crash is happening because method type argument inference finds the wrong type arguments.  This should be fixed by #979, but I'll see if I can fix the crash now.

Here's a slightly smaller test case.
```java
public class MapFile {
    public static <B, T extends B> void getOption(Class<T> cls, B[] opts) {
    }
    public static class ClassA {
        public static class InnerClassA {
            interface InnerInnerClassA {}
        }
    }
    public static class ClassB {
        public static abstract class InnerClassB { }
    }
    public static class ClassC {
        interface InterfaceClassC extends ClassA.InnerClassA.InnerInnerClassA { }
        private static class InnerClassC extends ClassA.InnerClassA implements InterfaceClassC { }
        public ClassC(ClassA.InnerClassA.InnerInnerClassA... opts) {
            // Does not crash
            MapFile.<ClassA.InnerClassA.InnerInnerClassA, InnerClassC>getOption(InnerClassC.class, opts);
            // Crashes
            MapFile.getOption(InnerClassC.class, opts);
        }
    }
}
```
