### ISSUE TITLE
[crash] AssertionError: @AssumeAssertion(nullness): currentNode is nonull if isRunning

### ISSUE THREAD

**Issue by cushon** [typetools/checker-framework#4115]
```java
import java.util.List;
import java.util.function.Function;

abstract class T {

  interface V {}

  abstract <F, T> Iterable<T> transform(Iterable<F> i, Function<? super F, ? extends T> f);

  abstract <E> List<E> copyOf(Iterable<? extends E> e);

  List<V> generateAppSuggestions(List<Integer> xs) {
    return copyOf(transform(xs, x -> new V() {}));
  }
}
```

```
./checker-framework-3.9.0/checker/bin/javac -processor Nullness T.java
error: SourceChecker.typeProcess: unexpected Throwable (AssertionError) while processing T.java; message: @AssumeAssertion(nullness): currentNode is nonull if isRunning.
  ; The Checker Framework crashed.  Please report the crash.
  Compilation unit: T.java
  Last visited tree at line 4 column 1:
  abstract class T {
  Exception: java.lang.AssertionError: @AssumeAssertion(nullness): currentNode is nonull if isRunning.; java.lang.AssertionError: @AssumeAssertion(nullness): currentNode is nonull if isRunning.
        at org.checkerframework.dataflow.analysis.AbstractAnalysis.getValue(AbstractAnalysis.java:187)
        at org.checkerframework.dataflow.analysis.AbstractAnalysis.getValue(AbstractAnalysis.java:280)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.getInferredValueFor(GenericAnnotatedTypeFactory.java:1738)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.addComputedTypeAnnotations(GenericAnnotatedTypeFactory.java:1689)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.addComputedTypeAnnotations(GenericAnnotatedTypeFactory.java:1636)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedTypeFromTypeTree(AnnotatedTypeFactory.java:1118)
        at org.checkerframework.framework.type.SupertypeFinder$SupertypeFindingVisitor.supertypesFromTree(SupertypeFinder.java:271)
        at org.checkerframework.framework.type.SupertypeFinder$SupertypeFindingVisitor.visitDeclared(SupertypeFinder.java:189)
        at org.checkerframework.framework.type.SupertypeFinder.directSuperTypes(SupertypeFinder.java:52)
        at org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType.directSuperTypes(AnnotatedTypeMirror.java:982)
        at org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:331)
        at org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Declared(AsSuperVisitor.java:29)
        at org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:314)
        at org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:65)
        at org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:98)
        at org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Typevar(AsSuperVisitor.java:379)
        at org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Typevar(AsSuperVisitor.java:29)
        at org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:344)
        at org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:65)
        at org.checkerframework.framework.type.AsSuperVisitor.visit(AsSuperVisitor.java:98)
        at org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Wildcard(AsSuperVisitor.java:398)
        at org.checkerframework.framework.type.AsSuperVisitor.visitDeclared_Wildcard(AsSuperVisitor.java:29)
        at org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:352)
        at org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visit(AbstractAtmComboVisitor.java:65)
```

**Comment by cushon** [comment]
> error: SourceChecker.typeProcess: unexpected Throwable (AssertionError) while processing T.java; message: @AssumeAssertion(nullness): currentNode is nonull if isRunning.

It looks like that assertion was re-introduced in ab9136c0eca1aab83ce1335dc47a033d0f50f917

https://github.com/typetools/checker-framework/blob/2d6ace442efb2102d0af355bb0a427dd8f763971/dataflow/src/main/java/org/checkerframework/dataflow/analysis/AbstractAnalysis.java#L187-L188
