### ISSUE TITLE
BugInCF: Unrecognized class: class java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by cushon** [typetools/checker-framework#4452]
We recently encountered the following crash in some code that was using dataflow as a library:

```
  Caused by: org.checkerframework.shaded.javacutil.BugInCF: Unrecognized class: class java.lang.OutOfMemoryError
  	at org.checkerframework.shaded.javacutil.TypesUtils.typeFromClass(TypesUtils.java:74)
  	at org.checkerframework.shaded.dataflow.cfg.builder.CFGTranslationPhaseOne.getTypeMirror(CFGTranslationPhaseOne.java:3744)
  	at org.checkerframework.shaded.dataflow.cfg.builder.CFGTranslationPhaseOne.<init>(CFGTranslationPhaseOne.java:395)
  	at org.checkerframework.shaded.dataflow.cfg.builder.CFGBuilder.build(CFGBuilder.java:67)
```

The root cause was that `CFGTranslationPhaseOne` tries to load a `TypeMirror` for `java.lang.OutOfMemoryError` here:

https://github.com/typetools/checker-framework/blob/562105de109198ca6206b1aeb9a46fe9e9420bb0/dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java#L395

and the affected compilation was invoking javac using a custom `-bootclasspath` that did not contain `java.lang.OutOfMemoryError`. (The use-case is Java code that is translated to JavaScript using [j2cl](https://github.com/google/j2cl); the custom bootclasspath contains APIs that are emulated in JavaScript, so `OutOfMemoryError` is deliberately not present.)

I realize this is a kind of unusual use-case. Would you be willing to consider accepting a patch to make `CFGTranslationPhaseOne` handle the case where `OutOfMemoryError` isn't available?

**Comment by mernst** [comment]
Liam, we would accept such a patch.  I agree it's weird, but I don't think it will make the code too much worse and we wish to help you with your use-case.

**Comment by cushon** [comment]
Thanks! I mailed a proposal.
