### ISSUE TITLE
Duplicate annotation @SideEffectFree in generated class file

### ISSUE THREAD

**Issue by glts** [typetools/checker-framework#502]
The Nullness Checker generates two `@SideEffectFree` annotations on `toString` when compiling the following class:

```java
public class Thing {
    @Override public String toString() {
        return "";
    }
}
```

Decompiled method:

```java
@SideEffectFree
@SideEffectFree
public String toString() {
    return "";
}
```

Use of run-time reflection will then result in an error.

```
...
Caused by: java.lang.annotation.AnnotationFormatError: Duplicate annotation for class: interface org.checkerframework.dataflow.qual.SideEffectFree: @org.checkerframework.dataflow.qual.SideEffectFree()
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:125) ~[na:1.8.0_51]
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72) ~[na:1.8.0_51]
	at java.lang.reflect.Executable.declaredAnnotations(Executable.java:602) ~[na:1.8.0_51]
	at java.lang.reflect.Executable.declaredAnnotations(Executable.java:600) ~[na:1.8.0_51]
	at java.lang.reflect.Executable.getDeclaredAnnotations(Executable.java:591) ~[na:1.8.0_51]
	at java.lang.reflect.Method.getDeclaredAnnotations(Method.java:629) ~[na:1.8.0_51]
...
```

I'm using the Checker Framework 1.9.5, Java 1.8.0_51.

**Comment by wmdietl** [comment]
Thanks for the test case! I can reproduce the issue and am looking into a fix.

**Comment by glts** [comment]
This fixes it, thanks.
