### ISSUE TITLE
Crash in AnnotatedTypeMirror.fromExpression

### ISSUE THREAD

**Issue by eikemeier** [typetools/checker-framework#5323]
Example repository at https://github.com/eikemeier/checker-framework-crash

Compilation crashes with
```
error: Error in AnnotatedTypeMirror.fromExpression(KeyForAnnotatedTypeFactory, withInformation): Cannot invoke "org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType.getUnderlyingType()" because "thisType" is null
  ; The Checker Framework crashed.  Please report the crash.
  Compilation unit: [...]/checker-framework-crash/src/main/java/com/example/Source.java
  Last visited tree at line 6 column 1:
  @Value.Immutable
  Exception: java.lang.NullPointerException: Cannot invoke "org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType.getUnderlyingType()" because "thisType" is null; java.lang.NullPointerException: Cannot invoke "org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType.getUnderlyingType()" because "thisType" is null
        at org.checkerframework.framework.type.AnnotatedTypeFactory.getImplicitReceiverType(AnnotatedTypeFactory.java:1987)
        at org.checkerframework.framework.type.TypeFromExpressionVisitor.visitIdentifier(TypeFromExpressionVisitor.java:217)
        at org.checkerframework.framework.type.TypeFromExpressionVisitor.visitIdentifier(TypeFromExpressionVisitor.java:75)
```

**Comment by mernst** [comment]
Thank you for the bug report (and our apologies that you encountered it).

If you are able to run the Checker Framework from source, could you please try the fix in #5327?
