### ISSUE TITLE
NullnessChecker fails in NetBeans 16 running om Windows 11

### ISSUE THREAD

**Issue by rkulzer** [typetools/checker-framework#5537]
Followed instructions in "37.13.1 Adding a checker via the Project Properties window" to add "org.checkerframework.checker.nullness.NullnessChecker" to the project.

According to NetBeans Help -> About, environment is as follows (with some redacting):

Product Version: Apache NetBeans IDE 16
Java: 19.0.1; Java HotSpot(TM) 64-Bit Server VM 19.0.1+10-21
Runtime: Java(TM) SE Runtime Environment 19.0.1+10-21
System: Windows 11 version 10.0 running on amd64; UTF-8; en_US (nb)
User directory: C:\Users\<redacted>\AppData\Roaming\NetBeans\16
Cache directory: C:\Users\<redacted>\AppData\Local\NetBeans\Cache\16

Ran the project build with following result:

An annotation processor threw an uncaught exception.
Consult the following stack trace for details.
java.lang.IllegalAccessError: class org.checkerframework.javacutil.AbstractTypeProcessor (in unnamed module @0x6536e911) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x6536e911
	at org.checkerframework.javacutil.AbstractTypeProcessor.init(AbstractTypeProcessor.java:97)
	at org.checkerframework.framework.source.SourceChecker.init(SourceChecker.java:543)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:696)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:823)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:919)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1262)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1377)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1234)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:916)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
BUILD FAILED (total time: 0 seconds)

**Comment by mernst** [comment]
Thanks for reporting this problem.  I'm sorry you are having trouble.

As you can see from the manual which mentions NetBeans 8, that part of the manual is out of date because I don't know of people who use NetBeans.  (Until now!  I hope you can help us improve the instructions.)

Since Java 11, additional command-line options are necessary.  The manual mentions the error you obtained in [section 37.6.2](https://checkerframework.org/manual/#javac-jdk11) (look for "cannot access").  That section also shows the additional command-line options that are necessary.  Could you please add them and see whether that solves your problem?

**Comment by rkulzer** [comment]
Mr. Ernst:
First of all, thank you for responding to my email.
Second, I must apologize. I violated my own rue for not "Read(ing) the Foolish Manual" (RTFM) (substitute your favorite word for "Foolish") prior to creating the Issue #5537.
I am only using NetBeans because I was scheduled to lake an Object-Oriented Design course and NetBeans was the preferred environment - I presume so that students had the same environment for sharing code during the project implementation part of the course.
With your reference to Section 37.6.2, et.al., I was able to get the Checker Framework working (to some extent).
As referenced in Section 37.13.1, NetBeans sets compiler options via the Compiling Dialog Window in the Additional Compiler Options text field. This required some minor "tweaks" to the additional options listed in Section 37.14.2. Specifically,
1. The options were copied and pasted into the Additional Compiler Options text field without the "javacOptions ++= Seq(" and terminating ")"
2. The options "-processorpath", "-cp", and "-processor" had to moved "outside" of the surrounding quote marks.
3. I had to use the fully qualified paths for the "$CHECKERFRAMEWORK" environment variable in the "-processorpath", and "-cp" options for the paths to the "checker.jar" and "-checker-qual.jar", respectively.

4. Something not specifically related to the Checker Framework, the "NullnessChecker" did not "like" that my code includes the following two packages "org.apiguardian.api.API" (GitHub - apiguardian-team/apiguardian: @API Guardian) and "org.netbeans.api.annotations.common". It complained that both of these packages "did not exist" when both of the respective jar files were included in the compile-time libraries list per Steps 2 in Section 37.13.1. 
As an aside, I found several older Checker Framework references to org.netbeans.api.annotations.common:

org.netbeans.api.annotations.common (checkerframework.org)
org.netbeans.api.annotations.common Class Hierarchy (checkerframework.org)
org.netbeans.api.annotations.common (javadoc.io)

Hope that this helps.
Randy Kulzer

-----Original Message-----
