### ISSUE TITLE
Nullness checker regression in 3.32 calling static method

### ISSUE THREAD

**Issue by jpschewe** [typetools/checker-framework#5717]
Using 3.31 this code was fine, using 3.32 this code has a nullness error referencing `classVariable` in the print statement.

```java

import org.checkerframework.checker.nullness.qual.Nullable;

public class ClassVariableNullable {

  private @Nullable Object classVariable;

  private void function() {
    if(null != classVariable) {
      System.out.println(classVariable.toString());
    } else {
      classVariable = new Object();
      method2(classVariable);
      System.out.println(classVariable.toString());
    }
  }

  private static void method2(final Object o) {
    System.out.println("method2: " + o.toString());
  }
}
```

Output
```
ClassVariableNullable.java:15: error: [dereference.of.nullable] dereference of possibly-null reference classVariable
      System.out.println(classVariable.toString());                         ^
```
I believe that the change mentioned in the release notes about side-effecting methods didn't take into account that static methods cannot modify class variables.

Or is the check here that another thread may modify `classVariable` between the execution of the lines of code?

**Comment by smillst** [comment]
Static methods can modify class variables:
```
import org.checkerframework.checker.nullness.qual.Nullable;

public class ClassVariableNullable {

  private @Nullable Object classVariable;

  private void function() {
    if(null != classVariable) {
      System.out.println(classVariable.toString());
    } else {
      classVariable = new Object();
      method2(classVariable, this);
      System.out.println(classVariable.toString());
    }
  }
  private static void method2(final Object o, ClassVariableNullable other) {
    System.out.println("method2: " + o.toString());
    other.classVariable = null;
  }
}
```
But a static method that can't access a private field can't modify it.  The follow should be legal, but currently isn't:
```
import org.checkerframework.checker.nullness.qual.Nullable;

public class ClassVariableNullable {

  private @Nullable Object classVariable;

  private void function() {
    if(null != classVariable) {
      System.out.println(classVariable.toString());
    } else {
      classVariable = new Object();
      Other.method2(classVariable, this);
      System.out.println(classVariable.toString());  // Should not error.
    }
  }
}
 class Other {
   private static void method2(final Object o, ClassVariableNullable other) {
    System.out.println("method2: " + o.toString());
    //  other.classVariable = null; // not legal Java because classVariable isn't accessible. 
  }
}
```

**Comment by jpschewe** [comment]
Sure, if you pass 'this' in, the class variable can be modified. However I didn't pass 'this' into the method.

**Comment by smillst** [comment]
In your first comment you said:
> I believe that the change mentioned in the release notes about side-effecting methods didn't take into account that static methods cannot modify class variables.

That example was to show that static methods can modify class variables.  Because this can happen, the Checker Framework has to conservatively assume it does. If you add `@SideEffectFree` to `method2`, then the Checker Framework knows that `method2` does not modify any fields.

**Comment by jpschewe** [comment]
Got it, so instead of checker reasoning about what parameters are passed the answer is to use the annotation, correct?
I'm assuming this is a performance trade off.

**Comment by jpschewe** [comment]
@smillst  here's one that really doesn't make sense:
```java

import java.io.File;

import org.checkerframework.checker.nullness.qual.Nullable;
import org.checkerframework.dataflow.qual.SideEffectFree;

// https://github.com/typetools/checker-framework/issues/5717
public class ClassVariableNullable2 {

  private @Nullable File mBestScheduleOutputFile = null;
  
  private void function() {
    if (null != mBestScheduleOutputFile) {
      if (!mBestScheduleOutputFile.delete()) {
        mBestScheduleOutputFile.deleteOnExit();
      }
    }
  }
  
}
```

```
ClassVariableNullable2.java:16: error: [dereference.of.nullable] dereference of possibly-null reference mBestScheduleOutputFile
        mBestScheduleOutputFile.deleteOnExit();
```

How can `mBestScheduleOutputFile` become null? I understand that the `delete` method may cause side-effects, however it's impossible for this method to assign back to the calling method.

This code is fine in 3.31 and gives the warning in 3.32.

**Comment by smillst** [comment]
```

import org.checkerframework.checker.nullness.qual.Nullable;
import org.checkerframework.dataflow.qual.SideEffectFree;

// https://github.com/typetools/checker-framework/issues/5717
public class ClassVariableNullable2 {
  private @Nullable File mBestScheduleOutputFile = null;

  private void function() {
    if (null != mBestScheduleOutputFile) {
      if (!mBestScheduleOutputFile.delete()) {
        mBestScheduleOutputFile.deleteOnExit();
      }
    }
  }

  public void makeNull() {
    mBestScheduleOutputFile = null;
  }

  public void test() {
    mBestScheduleOutputFile = new File(new OtherObject(this));
    function();
  }

  static class OtherObject {

    ClassVariableNullable2 cVN2;

    public OtherObject(ClassVariableNullable2 cVN2) {
      this.cVN2 = cVN2;
    }

    void makeNull() {
      cVN2.makeNull();
    }
  }

  static class File {

    OtherObject o;

    public File(OtherObject o) {
      this.o = o;
    }

    boolean delete() {
      o.makeNull();
      return false;
    }

    void deleteOnExit() { }
  }

  public static void main(String[] args) {
    new ClassVariableNullable2().test();
  }
}
```
If you run this, you get a NullPointerException:
```
$ javacheck ClassVariableNullable2.java
$ java ClassVariableNullable2
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "ClassVariableNullable2$File.deleteOnExit()" because "this.mBestScheduleOutputFile" is null
	at ClassVariableNullable2.function(ClassVariableNullable2.java:17)
	at ClassVariableNullable2.test(ClassVariableNullable2.java:28)
	at ClassVariableNullable2.main(ClassVariableNullable2.java:9)
```

Here's an example of how `mBestScheduleOutputFile` can become null.  Yes I had to rewrite `File` to do this, but the Nullness Checker doesn't know what `delete()` does other than it returns a primitive boolean.  Because `File#delete` may set `mBestScheduleOutputFile` to null, the Nullness Checker treats  `mBestScheduleOutputFile` as `@Nullable` after a call to `File#delete`.

**Comment by jpschewe** [comment]
OK, so the issue here is that it's a class variable and if the class is passed to the object that I'm calling the method on and if there's a method on this class to set the parameter to null, then one can get a null pointer. And given all of those options there's no way that checker can figure this out. Thank you for the explanation.
