### ISSUE TITLE
java.lang.IllegalAccessError in dataflow's CFG visualizer

### ISSUE THREAD

**Issue by FZhg** [typetools/checker-framework#5718]
I git-cloned the checker-framework repo and ran the test for constant propagation in Intellij with open-jdk18.

```
> Task :dataflow:ConstantPropagation.main() FAILED
Exception in thread "main" java.lang.IllegalAccessError: class org.checkerframework.dataflow.cfg.visualize.CFGVisualizeLauncher (in unnamed module @0x297e187e) cannot access class com.sun.tools.javac.util.Context (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.util to unnamed module @0x297e187e
	at org.checkerframework.dataflow.cfg.visualize.CFGVisualizeLauncher.generateMethodCFG(CFGVisualizeLauncher.java:223)
	at org.checkerframework.dataflow.cfg.visualize.CFGVisualizeLauncher.generateStringOfCFG(CFGVisualizeLauncher.java:309)
	at constantpropagation.ConstantPropagation.main(ConstantPropagation.java:32)

Execution failed for task ':dataflow:ConstantPropagation.main()'.
> Process 'command '/Users/zhangfan/Library/Java/JavaVirtualMachines/openjdk-18/Contents/Home/bin/java'' finished with non-zero exit value 1
```

It seems that the Context constructor from com.sun.tools.javac.util is not working.

Thanks!

**Comment by FZhg** [comment]
I managed to find a way around the bug by using JDK 11.
I also added extra path prefix in the inputfile
![image](https://user-images.githubusercontent.com/22489650/224495727-279d8844-8457-4f7e-bdf4-3313961f7821.png)

**Comment by mernst** [comment]
It sounds like this was an IntelliJ configuration issue.  Is that correct?  Should the manual be updated to indicate something that is important for IntelliJ configuration?
(This test is running in continuous integration on every commit, so I don't think it's related to a bug in the Checker Framework or the test.)

I'm glad this worked for you with JDK 11.  Did you try with JDK 17?  JDK 18 is no longer supported by Oracle.  But JDK 11 and 17 both are.

**Comment by FZhg** [comment]
> It sounds like this was an IntelliJ configuration issue. Is that correct? Should the manual be updated to indicate something that is important for IntelliJ configuration? (This test is running in continuous integration on every commit, so I don't think it's related to a bug in the Checker Framework or the test.)
> 
> I'm glad this worked for you with JDK 11. Did you try with JDK 17? JDK 18 is no longer supported by Oracle. But JDK 11 and 17 both are.

I have tried JDK 17. It didn't work as well.
I used gradle.

I think the solution is to add the following to the gradle properties. 

'''
org.gradle.jvmargs=--illegal-access=permit
'''

All libraries using the javac internal API seems to suffer the same issue.
