### ISSUE TITLE
MavenExample crashes with error "java.lang.NoSuchFieldError: RELEASE"

### ISSUE THREAD

**Issue by mdrost** [typetools/checker-framework#5727]
Hi, my project is crashing with the error "java.lang.NoSuchFieldError: RELEASE". I spent some time trying to figure out what I did wrong, given that exactly this error is mentioned in the manual. Then I tried to run MavenExample and I got the same error, so I will focus on MavenExample in this issue.  

I opened the MavenExample in Intellij IDEA 2022.2.3 (Community Edition), in MavenExample.java removed lines
```
@NonNull Object nn = nullable; // error on this line
System.out.println(nn);
```
so the project could theoretically be compiled and run.  
Then I clicked "compile" with output:
```
"C:\Program Files\Amazon Corretto\jdk1.8.0_332\bin\java.exe" -Dmaven.multiModuleProjectDirectory=D:\checker-framework\docs\examples\MavenExample "-Dmaven.home=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.3\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.3\plugins\maven\lib\maven3\bin\m2.conf" "-Dmaven.ext.class.path=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.3\plugins\maven\lib\maven-event-listener.jar" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.3\lib\idea_rt.jar=65244:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.3\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.3\plugins\maven\lib\maven3\boot\plexus-classworlds-2.6.0.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.3\plugins\maven\lib\maven3\boot\plexus-classworlds.license" org.codehaus.classworlds.Launcher -Didea.version=2022.2.3 compile
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< org.checkerframework:MavenExample >------------------
[INFO] Building MavenExample 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:properties (default) @ MavenExample ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ MavenExample ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\checker-framework\docs\examples\MavenExample\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ MavenExample ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to D:\checker-framework\docs\examples\MavenExample\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.322 s
[INFO] Finished at: 2023-03-21T17:54:02+01:00
[INFO] ------------------------------------------------------------------------

Process finished with exit code 0
```
And then I "run" the MavenExample.java, which build again the file (?) because in the "Build Output" tab I get output:
```
java: Error when invoking constructor org.checkerframework.checker.nullness.KeyForAnnotatedTypeFactory(class org.checkerframework.common.basetype.BaseTypeChecker) on args [org.checkerframework.checker.nullness.KeyForSubchecker@7bb2f57c]; cause: RELEASE
  ; The Checker Framework crashed.  Please report the crash.
  Exception: java.lang.NoSuchFieldError: RELEASE; java.lang.NoSuchFieldError: RELEASE
  	at org.checkerframework.javacutil.SystemUtil.getReleaseValue(SystemUtil.java:85)
  	at org.checkerframework.framework.stub.AnnotationFileElementTypes.<init>(AnnotationFileElementTypes.java:106)
  	at org.checkerframework.framework.type.AnnotatedTypeFactory.<init>(AnnotatedTypeFactory.java:547)
  	at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.<init>(GenericAnnotatedTypeFactory.java:324)
  	at org.checkerframework.checker.nullness.KeyForAnnotatedTypeFactory.<init>(KeyForAnnotatedTypeFactory.java:78)
  	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  	at org.checkerframework.common.basetype.BaseTypeChecker.invokeConstructorFor(BaseTypeChecker.java:337)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.createTypeFactory(BaseTypeVisitor.java:315)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.<init>(BaseTypeVisitor.java:265)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.<init>(BaseTypeVisitor.java:254)
  	at org.checkerframework.common.basetype.BaseTypeChecker.createSourceVisitor(BaseTypeChecker.java:259)
  	at org.checkerframework.common.basetype.BaseTypeChecker.createSourceVisitor(BaseTypeChecker.java:92)
  	at org.checkerframework.framework.source.SourceChecker.initChecker(SourceChecker.java:914)
  	at org.checkerframework.common.basetype.BaseTypeChecker.initChecker(BaseTypeChecker.java:114)
  	at org.checkerframework.common.basetype.BaseTypeChecker.initChecker(BaseTypeChecker.java:107)
  	at org.checkerframework.framework.source.SourceChecker.typeProcessingStart(SourceChecker.java:865)
  	at org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:165)
  	at com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
  	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
  	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  	at com.sun.tools.javac.main.Main.compile(Main.java:523)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:237)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.lambda$compileJava$2(JavaBuilder.java:524)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.invokeJavac(JavaBuilder.java:587)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:522)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:365)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:290)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:244)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1523)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1153)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1303)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:1118)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:889)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:471)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:197)
  	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:150)
  	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:357)
  	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:179)
  	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:218)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  	at java.lang.Thread.run(Thread.java:750)
```
Can you help me find the cause of the problem? Is it on my side or a bug in checker-framework?  
I have installed Amazon Corretto 8 if it makes a difference, and I cannot install something else.

I've only been learning java seriously for a month now so all those compiling/building processes are still quite dark magic for me.

ps. In my project for a few days I was able to somehow run it without error after randomly switching target/source versions in pom.xml file from 1.8 to 1.9 and back (with different combinations), because I read in manual about the need of Java 9+ compiler, but now it doesn't work (I don't remember exact steps I did and switching things randomly again was without success).

**Comment by smillst** [comment]
Like the manual says, this error means IntelliJ is using the wrong compiler.  So, the problem is with your IntelliJ setup. You may just need to tell IntelliJ to use Maven to build.  Here are the IntelliJ instructions: https://www.jetbrains.com/help/idea/delegate-build-and-run-actions-to-maven.html#delegate_to_maven.

**Comment by mdrost** [comment]
It worked, thanks!
