### ISSUE TITLE
IndexOutOfBoundsException in org.checkerframework.common.basetype.BaseTypeVisitor.checkTypeArguments

### ISSUE THREAD

**Issue by cushon** [typetools/checker-framework#6259]
```java
public class Y {

  public interface A {
    interface Builder<AT extends A> {
      AT build();
    }
  }

  public abstract static class B implements C {
    public abstract static class Builder<X> implements C.Builder<X, B> {}
  }

  public interface I<CT extends C, CBT extends C.Builder<?, ? extends CT>> {}

  public interface C {
    interface Builder<X, T extends C> {}
  }

  public static final class L implements I<B, B.Builder<String>> {}

  static class S<AT extends A, RT, CT extends C, CBT extends C.Builder<RT, CT>> {

    public static <
            ET extends A, E2 extends A.Builder<ET>, CT, IT extends C, I2 extends C.Builder<CT, IT>>
        S<ET, CT, IT, I2> assemble(I<IT, I2>... xs) {
      throw new AssertionError();
    }
  }

  void f(L f) {
    var storeStack = S.assemble(f);
  }
}
```

```
./checker-framework-3.39.0/checker/bin/javac -processor Nullness Y.java
error: SourceChecker.typeProcess: unexpected Throwable (IndexOutOfBoundsException) while processing Y.java; message: Index: 1, Size: 1
  ; The Checker Framework crashed.  Please report the crash.  Version: Checker Framework 3.39.0.
  Compilation unit: Y.java
  Last visited tree at line 31 column 5:
      var storeStack = S.assemble(f);
  Exception: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1; java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
  	at jdk.compiler/com.sun.tools.javac.util.List.get(List.java:476)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.checkTypeArguments(BaseTypeVisitor.java:3372)
  	at org.checkerframework.common.basetype.BaseTypeValidator.visitParameterizedType(BaseTypeValidator.java:557)
  	at org.checkerframework.common.basetype.BaseTypeValidator.visitDeclared(BaseTypeValidator.java:339)
  	at org.checkerframework.common.basetype.BaseTypeValidator.visitDeclared(BaseTypeValidator.java:56)
  	at org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType.accept(AnnotatedTypeMirror.java:1054)
  	at org.checkerframework.framework.type.visitor.AnnotatedTypeScanner.scan(AnnotatedTypeScanner.java:206)
  	at org.checkerframework.framework.type.visitor.AnnotatedTypeScanner.visitWildcard(AnnotatedTypeScanner.java:357)
  	at org.checkerframework.common.basetype.BaseTypeValidator.visitWildcard(BaseTypeValidator.java:675)
  	at org.checkerframework.common.basetype.BaseTypeValidator.visitWildcard(BaseTypeValidator.java:56)
  	at org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedWildcardType.accept(AnnotatedTypeMirror.java:2168)
  	at org.checkerframework.framework.type.visitor.AnnotatedTypeScanner.scan(AnnotatedTypeScanner.java:206)
  	at org.checkerframework.common.basetype.BaseTypeValidator.visitDeclared(BaseTypeValidator.java:365)
  	at org.checkerframework.common.basetype.BaseTypeValidator.visitDeclared(BaseTypeValidator.java:56)
  	at org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType.accept(AnnotatedTypeMirror.java:1054)
  	at org.checkerframework.framework.type.visitor.AnnotatedTypeScanner.scan(AnnotatedTypeScanner.java:206)
  	at org.checkerframework.framework.type.visitor.AnnotatedTypeScanner.visit(AnnotatedTypeScanner.java:194)
  	at org.checkerframework.common.basetype.BaseTypeValidator.isValid(BaseTypeValidator.java:112)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.validateType(BaseTypeVisitor.java:4792)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.commonAssignmentCheck(BaseTypeVisitor.java:2921)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.visitVariable(BaseTypeVisitor.java:1552)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.visitVariable(BaseTypeVisitor.java:186)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:1040)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
  	at org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:92)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:405)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:186)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:272)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1104)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
  	at org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:92)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:405)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:186)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:224)
  	at org.checkerframework.framework.source.SourceVisitor.visitMethod(SourceVisitor.java:110)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.visitMethod(BaseTypeVisitor.java:1043)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.visitMethod(BaseTypeVisitor.java:186)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:948)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
  	at org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:92)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:405)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:186)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:203)
  	at org.checkerframework.framework.source.SourceVisitor.visitClass(SourceVisitor.java:98)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.processClassTree(BaseTypeVisitor.java:612)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:558)
  	at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:186)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:855)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:66)
  	at org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:86)
  	at org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:1046)
  	at org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:558)
  	at org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:551)
  	at org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:188)
  	at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:876)
  	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:133)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1435)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1392)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:978)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:319)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:178)
  	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
  	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
```

**Comment by smillst** [comment]
Fixed via #6262.
