### ISSUE TITLE
Checker Framework 3.38.0 gets stuck processing enums

### ISSUE THREAD

**Issue by cushon** [typetools/checker-framework#6319]
Version 3.38.0 and newer of the Checker Framework seem to get stuck processing the following example. Earlier versions complete quickly, after 3.38.0 it runs for >15 minutes and appears to be stuck:

```java
import static java.util.Comparator.comparing;
import static java.util.stream.Collectors.toList;

import java.util.List;

class T {
  void f(List<? extends Enum<?>> list) {
    for (Enum<?> value : list.stream().sorted(comparing(Enum::name)).collect(toList())) {}
  }
}
```

```
$ javac -fullversion
javac full version "11.0.16+8"
$ javac -J--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED -J--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED -processor org.checkerframework.checker.nullness.NullnessChecker -sourcepath : -processorpath checker-framework-3.38.0/checker/dist/checker.jar -cp checker-framework-3.38.0/checker/dist/checker-qual.jar T.java
```

The stack dump shows many repetitions of these frames:

```
        at org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:612)
        at org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:258)
        at org.checkerframework.framework.type.DefaultTypeHierarchy.isContainedBy(DefaultTypeHierarchy.java:411)
        at org.checkerframework.framework.type.DefaultTypeHierarchy.isContainedMany(DefaultTypeHierarchy.java:647)
        at org.checkerframework.framework.type.DefaultTypeHierarchy.visitTypeArgs(DefaultTypeHierarchy.java:607)
        at org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:550)
        at org.checkerframework.framework.type.DefaultTypeHierarchy.visitDeclared_Declared(DefaultTypeHierarchy.java:48)
        at org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:312)
        at org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:258)
        at org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtypeCaching(DefaultTypeHierarchy.java:314)
        at org.checkerframework.framework.type.DefaultTypeHierarchy.visitTypevar_Type(DefaultTypeHierarchy.java:1188)
        at org.checkerframework.framework.type.DefaultTypeHierarchy.visitTypevar_Declared(DefaultTypeHierarchy.java:931)
        at org.checkerframework.framework.type.DefaultTypeHierarchy.visitTypevar_Declared(DefaultTypeHierarchy.java:48)
        at org.checkerframework.framework.util.AtmCombo.accept(AtmCombo.java:588)
        at org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:258)
        at org.checkerframework.framework.type.DefaultTypeHierarchy.isSubtype(DefaultTypeHierarchy.java:136)
        at org.checkerframework.framework.type.DefaultTypeHierarchy.isContainedWithinBounds(DefaultTypeHierarchy.java:449)        at org.checkerframework.framework.type.DefaultTypeHierarchy.visitTypevar_Typevar(DefaultTypeHierarchy.java:1004)
        at org.checkerframework.framework.type.DefaultTypeHierarchy.visitTypevar_Typevar(DefaultTypeHierarchy.java:48)
```

**Comment by smillst** [comment]
This bug was introduced by 56b1eee1e84b654bf672e61567896c644054876e.

The test case can be even further simplified to:
```
 Comparator<Enum<?>> c = Comparator.comparing(Enum::name);
```

I'll work on fixing this.
