### ISSUE TITLE
Crash when trying to use latest snapshot version of Checker dataflow

### ISSUE THREAD

**Issue by msridhar** [typetools/checker-framework#6327]
To reproduce, do `./gradlew publishToMavenLocal` in the Checker Framework repo, then check out https://github.com/msridhar/NullAway/tree/cf-3.40.1-snapshot, and finally run `./gradlew :sample:compileJava` in the NullAway repo.  I get a crash (this is with JDK 17), relevant stack:

```
 Caused by: org.checkerframework.nullaway.javacutil.UserError: Configuration problem! Could not load type: org.checkerframework.dataflow.qual.AssertMethod
        at org.checkerframework.nullaway.javacutil.TreeUtils.getMethods(TreeUtils.java:1332)
        at org.checkerframework.nullaway.javacutil.TreeUtils.getMethod(TreeUtils.java:1276)
        at org.checkerframework.nullaway.javacutil.TreeUtils.getMethod(TreeUtils.java:1257)
        at org.checkerframework.nullaway.dataflow.cfg.builder.CFGTranslationPhaseOne.<init>(CFGTranslationPhaseOne.java:462)
        at com.uber.nullaway.dataflow.cfg.NullAwayCFGBuilder$NullAwayCFGTranslationPhaseOne.<init>(NullAwayCFGBuilder.java:112)
        at com.uber.nullaway.dataflow.cfg.NullAwayCFGBuilder.build(NullAwayCFGBuilder.java:70)
        at com.uber.nullaway.dataflow.DataFlow$2.load(DataFlow.java:137)
        at com.uber.nullaway.dataflow.DataFlow$2.load(DataFlow.java:102)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3571)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2313)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2190)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2080)
```

This looks like the relevant code:

https://github.com/typetools/checker-framework/blob/49d97d7ea18562d644a98699acd82825f0e97245/dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java#L462-L465

Will this code only work if the `checker-qual` artifact is in the classpath of the program being compiled?  If so, can we do things in a different way that removes that requirement?  This requirement won't work for NullAway users.

**Comment by msridhar** [comment]
FYI @smillst
