### ISSUE TITLE
Arguments list too long when doing `git commit`

### ISSUE THREAD

**Issue by CharlesZ-Chen** [typetools/checker-framework#838]
Today I try to do a git commit on my local branch of checker-framework, and I get below error after I do a `git commit`:
```bash
check-format:
Getting: https://raw.githubusercontent.com/mernst/plume-lib/master/bin/check-google-java-format.py
To: /Users/charleszhuochen/Programming/UWaterloo/jsr308/checker-framework/checker/bin-devel/check-google-java-format.py

BUILD FAILED
/Users/charleszhuochen/Programming/UWaterloo/jsr308/checker-framework/build.xml:245: Execute failed: java.io.IOException: Cannot run program "python": error=7, Argument list too long
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
	at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:428)
	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:442)
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:629)
	at org.apache.tools.ant.taskdefs.ExecuteOn.runParallel(ExecuteOn.java:715)
	at org.apache.tools.ant.taskdefs.ExecuteOn.runExec(ExecuteOn.java:478)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:496)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:853)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
Caused by: java.io.IOException: error=7, Argument list too long
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 25 more
```

Does anyone knows how to solve this problem? Thanks!

**Comment by CharlesZ-Chen** [comment]
I tried a test `git commit` on typetools master branch, and I meet the same problem.

**Comment by mernst** [comment]
What operating system are you running?
MacOSX has small values for ARG_MAX that may cause problems.  Run these commands:
```
getconf ARG_MAX
expr `getconf ARG_MAX` - `env|wc -c` - `env|wc -l` \* 4 - 2048
```

For me (Linux) they output the following values, respectively:

2180000
2165306

It's a mystery why Apple would choose smaller values.

Can you confirm what is in
checker-framework/checker/bin-devel/git.pre-commit
and checker-framework/.git/hooks/pre-commit?

Neither should contain "ant check-format".

If both do, then you haven't pulled master into your clone.  (Beware of
formatting changes when you do -- see Suzanne's email or the instructions
at the bottom of plume-lib/bin/run-google-java-format.py.)

If only the second does, then you probably haven't run any ant targets,
such as tests, after the merge.  Running "ant prep" in directory
checker-framework/checker is enough to update the latter file.

**Comment by CharlesZ-Chen** [comment]
Thanks a lot for providing the useful information! After running "ant prep" in `checker-framework/checker`, now I can smoothly commit my changes using git again. Below are my investigations towards you questions:

> What operating system are you running?
I use MacOSX. And the ARG_MAX values of mine are:

262144

258509

> Can you confirm what is in
checker-framework/checker/bin-devel/git.pre-commit
and checker-framework/.git/hooks/pre-commit?

I checked both files, they all not contain "ant check-format".

---

"stack trace" of my problem before:
0. My operating system: Mac OSX 10.10.5, My values for ARG_MAX by running the commands you provided are:

```
262144
258509
```

1. I pulled newest changes of CF from master branch of typetools into my clone.

2. I tried to commit my own changes based on the merged code base.

3. I got the "Argument list too long" error.

4. After I running "ant prep" in `checker-framework/checker` directory, the "argument list too long" error disappeared.

Hope this "stack trace" might be helpful for other Mac OS X developers if they meet the same problem.

**Comment by CharlesZ-Chen** [comment]
This issue still not solved.

I make a new clone of typetools/master in my local machine:

```git clone https://github.com/typetools/checker-framework.git```

And then in the clone, running `ant reformat` I would get `argument list too long`  error:

```

uildfile: /Users/charleszhuochen/Programming/UWaterloo/sandbox/checker-framework/build.xml

reformat:
      [get] Getting: https://raw.githubusercontent.com/mernst/plume-lib/master/bin/run-google-java-format.py
      [get] To: /Users/charleszhuochen/Programming/UWaterloo/sandbox/checker-framework/checker/bin-devel/run-google-java-format.py

BUILD FAILED
/Users/charleszhuochen/Programming/UWaterloo/sandbox/checker-framework/build.xml:238: Execute failed: java.io.IOException: Cannot run program "python": error=7, Argument list too long
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
	at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:428)
	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:442)
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:629)
	at org.apache.tools.ant.taskdefs.ExecuteOn.runParallel(ExecuteOn.java:715)
	at org.apache.tools.ant.taskdefs.ExecuteOn.runExec(ExecuteOn.java:478)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:496)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:853)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
Caused by: java.io.IOException: error=7, Argument list too long
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 25 more

```

Does anyone know how to solve this problem?  I tried to google "increase ARG_MAX on mac" but I don't get any relate tutorial of that.

Thanks!

**Comment by CharlesZ-Chen** [comment]
I tried running `./.travis-build.sh` in the clone, and it failed when running `ant reformat` as the same reason.

**Comment by CharlesZ-Chen** [comment]
I also tried running `ant prep` in checker dir. But it doesn't work.

**Comment by CharlesZ-Chen** [comment]
The solution please refer to issue #850
