### ISSUE TITLE
Improper formatting when doing git commit

### ISSUE THREAD

**Issue by CharlesZ-Chen** [typetools/checker-framework#850]
I tried commit some changes on my local clone of Checker Framework.

But I get `Improper formatting: framework/src/org/checkerframework/framework/type/AnnotatedTypeMirror.java` error when try to commit my local changes.

I'm sure I don't mis-introduce tab indentations, and also other formatting looks good:

```java
-            AnnotationMirror anno = qualHier.findCorrespondingAnnotation(aliased, annotations);
+
+            AnnotationMirror anno = null;
+            if (this.getKind() == TypeKind.INTERSECTION) {
+                anno = qualHier.findCorrespondingAnnotation(aliased, this.directSuperTypes().get(0).getAnnotations());
+            } else {
+                anno = qualHier.findCorrespondingAnnotation(aliased, annotations);
+            }
+
```

Does anyone know how to solve this problem? What format exactly checker framework would check before committing changes?

Thanks a lot!

**Comment by smillst** [comment]
The Checker Framework follows the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html) with the exception of indenting with 4 spaces instead of 2.  To reformat the code so that you can commit changes, run `ant reformat`.

**Comment by CharlesZ-Chen** [comment]
Hi smillst, I tried running `ant reformat`, but I got error:

```
/Users/charleszhuochen/Programming/UWaterloo/jsr308/checker-framework/build.xml:238: Execute failed: java.io.IOException: Cannot run program "python": error=7, Argument list too long
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
	at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:428)
	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:442)
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:629)
	at org.apache.tools.ant.taskdefs.ExecuteOn.runParallel(ExecuteOn.java:715)
	at org.apache.tools.ant.taskdefs.ExecuteOn.runExec(ExecuteOn.java:478)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:496)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:853)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
```

My OS is Mac, and I meet this error before, but last time it automatically disappeared while this time it doesn't...

Is currently `ant reformat` doesn't support Mac OS?

Thanks!

**Comment by smillst** [comment]
Seems like last time you ran `ant prep` and that fix this error:
https://github.com/typetools/checker-framework/issues/838#issuecomment-232439526

**Comment by CharlesZ-Chen** [comment]
Yes, it works on last time. But this time I tried `ant prep` again, and it doesn't work...

**Comment by smillst** [comment]
>Is currently ant reformat doesn't support Mac OS?

I'm using OS X Yosemite (10.10.5) and ant reformat works.

**Comment by CharlesZ-Chen** [comment]
Hi Smillst, do you modified your `ARG_MAX` in your mac? I still get `argument list too long` when running `ant reformat`, and thus I cannot commit anything.... 

Thanks!

**Comment by smillst** [comment]
> do you modified your ARG_MAX in your mac?

No.  What version of OS X are you using?

**Comment by CharlesZ-Chen** [comment]
I also using OS X Yosemite (10.10.5), the same version as yours.

**Comment by smillst** [comment]
Try adding the maxparallel parameter -- see diff below. If you still get the error try decreasing 4096.

````
diff --git a/build.xml b/build.xml
index 3ab1685..3651128 100644
--- a/build.xml
+++ b/build.xml
@@ -235,7 +235,7 @@
           description="Reformat Java code">
     <get src="${run-gjf-website-dir}/run-google-java-format.py" dest="checker/bin-devel/" usetimestamp="true" ignoreerrors="true"/>
     <chmod file="checker/bin-devel/run-google-java-format.py" perm="+x"/>
-    <apply executable="python" parallel="true" failonerror="true">
+    <apply executable="python" parallel="true" maxparallel="4096" failonerror="true">
       <arg value="./checker/bin-devel/run-google-java-format.py"/>
       <arg value="--aosp"/>    <!-- 4-space indentation -->
       <fileset refid="formatted.java.files"/>
````

**Comment by CharlesZ-Chen** [comment]
Thanks a lot! `maxparallel="2048" doesn't work for my Mac, I tried `maxparallel="1024"`, and it works!

**Comment by smillst** [comment]
Great!   I'm going to leave this issue open until we come up with a way to set maxparallel only if it is needed.
