### ISSUE TITLE
Unsupported major.minor version 52.0 when building checker framework using java7 in Mac

### ISSUE THREAD

**Issue by CharlesZ-Chen** [typetools/checker-framework#856]
System Environment:

- Mac 10.10.5 Yosemite (14F1808)

- `$JAVA_HOME`: /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home

- `java -version`: 
```
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
```
- `javac -version`: javac 1.7.0_79

Reproduce steps:

1. clone typetools master branch:
```git clone https://github.com/typetools/checker-framework.git```
2. In the clone, run ```./.travis-build.sh```

I get:

```
[exec] cd nullness; /Applications/Xcode.app/Contents/Developer/usr/bin/make jaifs
     [exec] Exception in thread "main" java.lang.UnsupportedClassVersionError: annotations/io/classfile/ClassFileReader : Unsupported major.minor version 52.0
     [exec] 	at java.lang.ClassLoader.defineClass1(Native Method)
     [exec] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
     [exec] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
     [exec] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
     [exec] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
     [exec] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
     [exec] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
     [exec] 	at java.security.AccessController.doPrivileged(Native Method)
     [exec] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
     [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
     [exec] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
     [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
     [exec] 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
     [exec] make[2]: *** [build/java/beans/FeatureDescriptor.jaif] Error 1
     [exec] make[1]: *** [nullness.jaifs] Error 2
     [exec] make: *** [all] Error 2

BUILD FAILED
/Users/charleszhuochen/Programming/UWaterloo/sandbox/checker-framework/build.xml:19: The following error occurred while executing this line:
/Users/charleszhuochen/Programming/UWaterloo/sandbox/checker-framework/checker/build.xml:1404: exec returned: 2
```

I tried the same steps under RedHat 7.2 and Checker Framework was build successful.

I only get this error under Mac. I guess there are some Java8 generated classes, but I already set my JAVA_HOME to 1.7, which is very weird to get the unsupported version error.

Does anyone could give me some clues to solve this problem?

Thanks a lot!

**Comment by smillst** [comment]
`annotations/io/classfile/ClassFileReader` is defined in annotation-file-utilities which is in annotation-tools.  Try running `ant clean` in annotation-tools, and then rebuilding.
